import { buildPageEntry, type PageEntry } from "@/lib/marketing-page-data"

const primary = { label: "Book a Demo", href: "/company/book-demo" }
const secondary = { label: "Contact Us", href: "/company/contact" }

const companySeeds = [
  {
    slug: "about",
    title: "About Omniweb",
    summary: "The team, the mission, and the story behind Omniweb's AI revenue platform.",
    overview: [
      "Omniweb was built from a simple observation: small and mid-sized businesses were losing revenue every day not because they lacked good products or skilled teams, but because their customer communication infrastructure could not keep up with demand. Calls went unanswered after hours. Web inquiries sat in an inbox until Monday. Qualified leads went cold while the business was busy doing the actual work they had built the business to do.",
      "We started building Omniweb to address this gap — to give businesses that could not afford a 24/7 receptionist team the ability to respond to every lead, qualify every inquiry, and book every appointment regardless of when the customer reached out. The technology existed. The infrastructure to deliver it as a product that small and mid-sized businesses could actually implement and afford did not.",
      "Today, Omniweb is deployed across thousands of businesses in over a dozen industries — from solo contractors and local service businesses to multi-location healthcare practices, e-commerce stores, and AI agencies managing portfolios of client deployments. The common thread is that every one of them is capturing revenue they were losing before.",
      "Our team is built around the belief that AI should work for the businesses that need it most — not just the ones with enterprise budgets and engineering departments. Every product decision we make is evaluated against that belief: is this making AI more accessible, more effective, and more valuable for the real businesses using it?",
    ],
    problem: "Small and mid-sized businesses lack the communication infrastructure to compete with larger operations that can staff 24/7 response teams. The result is missed leads, slow response times, and revenue that goes to competitors who simply picked up the phone.",
    solution: "Omniweb's AI voice and chat platform gives every business the communication infrastructure of a much larger operation — without the headcount, the overhead, or the complexity of building it from scratch.",
    valueToIndustry: "When AI makes 24/7 professional communication accessible to small businesses, the competitive landscape shifts. Smaller operations can win on responsiveness and customer experience, not just on price.",
    valueToUser: "You run a better business — one that never misses a lead, always has a professional response ready, and grows its revenue from the customer base it is already building.",
    outcome: "More revenue captured from existing demand. A business that operates at a higher level of professionalism and responsiveness. A foundation for growth that does not depend on adding headcount to handle communication.",
    features: [
      "Founded by operators who experienced the problem firsthand",
      "Mission-driven product development prioritizing SMB accessibility",
      "Thousands of businesses deployed across 12+ industries",
      "Team of AI engineers, product designers, and industry specialists",
      "Commitment to transparent pricing and honest business practices",
      "Customer success team that treats every deployment as a partnership",
      "Active product roadmap driven by customer feedback",
      "Built on enterprise-grade infrastructure accessible at every price point",
    ],
    useCases: [
      "Prospective customers researching the company before making a buying decision",
      "Job seekers evaluating Omniweb as an employer",
      "Partners and agencies exploring the Omniweb partnership program",
      "Investors and analysts researching the company",
      "Journalists and researchers covering AI in business",
    ],
    howItWorks: [
      "Read about our founding story, mission, and the team behind the product on this page.",
      "Explore our values and approach to building AI for real businesses — not just enterprise accounts.",
      "If you want to talk to someone on the team, use the Book a Demo link to schedule a conversation or reach out through the contact page.",
    ],
    faq: [
      { question: "Where is Omniweb based?", answer: "Omniweb is headquartered in the United States with a distributed team working across multiple time zones. Our infrastructure is US-based with EU-region availability for GDPR compliance." },
      { question: "Is Omniweb a venture-backed startup?", answer: "We are a privately held company. We have chosen to grow based on customer revenue rather than venture capital, which means our product roadmap and business decisions are driven by what our customers actually need." },
    ],
    related: ["/company/careers", "/company/partners", "/resources/case-studies"],
  },
  {
    slug: "contact",
    title: "Contact Omniweb",
    summary: "Get in touch with our team for sales, support, partnerships, or general inquiries.",
    overview: [
      "Whether you are evaluating Omniweb for your business, need help with an existing deployment, want to discuss a partnership, or have a question that our documentation did not answer — this page connects you to the right person on our team.",
      "We respond to sales inquiries within one business day. Support requests for active customers are handled based on plan tier — standard support averages under four hours, and enterprise support is under one hour. Partnership and integration inquiries are reviewed by our partnerships team and typically receive a response within two business days.",
      "If you are not sure which contact category applies to your question, use the general inquiry form. We will route your message to the right team and make sure you get a response. We do not use sales automation to route inquiries into a sequence without a real human review.",
    ],
    problem: "Contact pages at software companies are often designed to funnel everyone into a demo request, even when the question is not about buying the product. This creates friction for customers who need support, partners exploring integration, or media contacts with legitimate inquiries.",
    solution: "Omniweb's contact page routes inquiries to the right team based on the nature of the request — sales, support, partnerships, press, or general. Every inquiry gets a real human response, not an automated sequence.",
    valueToIndustry: "Responsive vendor communication is a signal of organizational health. Businesses that answer their own contact forms promptly build the trust that converts interested parties into customers.",
    valueToUser: "You reach the right person quickly regardless of what your question is about. Your inquiry is treated as a real communication, not a CRM event.",
    outcome: "Fast, appropriate routing of every inquiry. Real human responses on realistic timelines. No automated deflection for questions that deserve a direct answer.",
    features: [
      "Sales inquiry form with same-day response commitment",
      "Support ticket submission for existing customers",
      "Partnership and integration inquiry routing",
      "Press and media contact for journalists and analysts",
      "General inquiry option for questions that do not fit other categories",
      "Office location and mailing address",
      "Phone number for urgent inquiries",
      "Live chat during business hours",
    ],
    useCases: [
      "Prospective customers with specific questions before purchasing",
      "Existing customers needing support with their deployment",
      "Partners exploring integration or reseller opportunities",
      "Press and media contacts seeking information or interviews",
      "Job seekers with questions not answered on the careers page",
    ],
    howItWorks: [
      "Select the category that best matches your inquiry type from the form options. This routes your message to the team best equipped to respond.",
      "Complete the form with enough context for us to give you a useful response without a follow-up question to clarify what you are asking.",
      "Expect a response within the timeframe stated for your inquiry category. Sales and general inquiries receive a response within one business day.",
    ],
    faq: [
      { question: "What is the best way to reach someone immediately?", answer: "For urgent matters, the live chat on this page is staffed during business hours. For platform-affecting incidents, existing customers should use the priority support channel in their account dashboard." },
      { question: "Can I call someone directly?", answer: "Yes. Our main support line is available during business hours for existing customers. The number is provided in your account dashboard. Sales inquiries are handled by our team via the form and live chat." },
    ],
    related: ["/resources/help-center", "/company/book-demo", "/company/about"],
  },
  {
    slug: "book-demo",
    title: "Book a Demo",
    summary: "See Omniweb in action with a personalized demo tailored to your industry and use case.",
    overview: [
      "The Omniweb demo is not a sales pitch presentation. It is a working session where we show you the platform operating on a use case that matches your specific business — your industry, your customer interaction type, and your current workflow. You see real AI conversations, real configuration options, and real performance data from similar deployments.",
      "Before the demo, we ask you a few questions about your business: what industry you are in, how many leads or calls you handle per month, what your current process is for handling them, and what outcome you are most hoping AI will produce. This preparation lets us show you the parts of the platform that are most relevant to you, rather than walking through every feature regardless of relevance.",
      "The demo typically runs 30 to 45 minutes. By the end, you will have seen how the AI would handle your specific use case, asked the questions you came in with, and received an honest assessment of whether Omniweb is the right fit — including what would need to be true for it to work well for your business.",
      "After the demo, the next step is always a free trial — not a proposal, not a contract. You get 30 days with full access to configure and test the platform yourself before deciding whether to subscribe.",
    ],
    problem: "Most software demos show a polished set of generic features rather than answering the specific question the prospect actually has: will this work for my business, in my industry, with my customers? Generic demos waste time and delay decisions.",
    solution: "Omniweb's demo is prepared based on your specific business context before you arrive. You see the platform operating on your use case with your industry's typical customer interactions — not a generic demonstration designed to impress rather than inform.",
    valueToIndustry: "Personalized, honest demos accelerate buying decisions and reduce post-purchase disappointment. When prospects understand exactly what they are getting before they commit, they implement more successfully.",
    valueToUser: "You spend 45 minutes seeing whether Omniweb actually addresses your specific problem rather than watching a presentation about general AI capabilities. You leave with a clear answer.",
    outcome: "A clear, honest assessment of whether Omniweb is right for your business — based on your actual use case, not a generic fit calculation.",
    features: [
      "Pre-demo intake to customize the session for your business",
      "Live AI demonstration on your industry use case",
      "Configuration walkthrough tailored to your workflow",
      "Performance data from similar industry deployments",
      "Honest assessment of fit and realistic expectations",
      "Q&A with a product specialist — not a sales script",
      "Clear next steps — trial, enterprise evaluation, or alternative recommendation",
      "30-day free trial offered immediately after the session",
    ],
    useCases: [
      "Business owners evaluating AI for the first time and wanting to see it before committing",
      "Operations leaders assessing integration requirements before a platform decision",
      "Agency owners evaluating Omniweb for client deployment",
      "Enterprise buyers requiring a technical deep dive before procurement",
      "Teams with specific workflow requirements that need to be validated",
    ],
    howItWorks: [
      "Complete the pre-demo form with your business context. This takes about three minutes and lets us prepare a session that is actually relevant to you.",
      "Select a time slot from the booking calendar. Demo sessions are available Monday through Friday across multiple time zones.",
      "Attend the 30-45 minute session. Ask every question you have. We will be honest about what the platform does and does not do well for your specific use case.",
    ],
    faq: [
      { question: "Who will be on the demo call?", answer: "A product specialist who has experience with your industry and use case. They are not a generic SDR — they will know your business type before the call starts because you told us in the intake form." },
      { question: "What happens after the demo?", answer: "If it looks like a good fit, we set you up with a 30-day free trial immediately. If it is not a fit, we will tell you that and may be able to suggest an alternative approach." },
    ],
    related: ["/company/contact", "/pricing/combo", "/resources/case-studies"],
  },
  {
    slug: "partners",
    title: "Partner Program",
    summary: "Build a business around Omniweb — as a reseller, integration partner, or referral affiliate.",
    overview: [
      "The Omniweb Partner Program is designed for three types of organizations: agencies and consultants who deploy Omniweb for clients, technology companies who want to integrate Omniweb's AI capabilities into their own products, and referral partners who earn a commission for introducing qualified businesses to the platform.",
      "Agency partners get access to the multi-tenant platform, wholesale pricing, white-labeling, and the deployment resources they need to serve clients efficiently. The agency partner relationship is designed to be commercially durable — the better your clients perform, the stronger the relationship and the better your pricing.",
      "Technology integration partners get API access, integration documentation, co-marketing support, and listing in the Omniweb integrations directory. If your platform serves businesses that would benefit from AI voice or chat, the integration conversation is worth having.",
      "Referral partners earn a commission on subscriptions from businesses they refer to Omniweb. If you advise, consult with, or have relationships with businesses that would benefit from AI revenue systems, the referral program is a straightforward way to participate in the value you help create.",
    ],
    problem: "Most SaaS partner programs are designed for the vendor's benefit rather than the partner's. They create volume requirements, restrict margin, and require investment before the economics are proven. The result is partners who participate nominally but do not commit seriously.",
    solution: "Omniweb's partner program is built around the economics that make agency and referral relationships sustainable: fair wholesale pricing, clear commission structures, real deployment support, and a platform that actually delivers results for clients.",
    valueToIndustry: "Strong partner programs extend AI access to businesses that would not discover or deploy it independently. The industry benefits when good AI reaches more businesses through capable partners.",
    valueToUser: "You build a commercially viable practice around technology that works. Your clients get better outcomes because you are working with a platform built for delivery, not just marketing.",
    outcome: "Sustainable economics for your partnership with Omniweb. Better client outcomes from a platform built for agency deployment. A revenue stream that grows with your client success.",
    features: [
      "Agency multi-tenant management with white-label options",
      "Wholesale pricing that improves with portfolio size",
      "Referral commission program with transparent tracking",
      "API and integration documentation for technology partners",
      "Co-marketing opportunities and integration directory listing",
      "Dedicated partner success contact",
      "Partner training and certification program",
      "Early access to new features for partner feedback",
    ],
    useCases: [
      "Marketing and AI agencies adding Omniweb deployments to their service offering",
      "Business consultants recommending AI solutions to their clients",
      "Technology platforms integrating AI voice and chat for their user base",
      "Franchise systems partnering with Omniweb for system-wide AI deployment",
      "Individuals with strong networks in business verticals where Omniweb is a clear fit",
    ],
    howItWorks: [
      "Review the partner program details for the partnership type that matches your model — agency, integration, or referral. Each has its own application and onboarding process.",
      "Apply through the partner inquiry form. Our partnerships team reviews applications and responds within two business days.",
      "Once approved, agency and integration partners receive access to the partner portal, deployment resources, and their dedicated partner success contact.",
    ],
    faq: [
      { question: "Is there a minimum volume requirement to join the agency program?", answer: "There is no minimum volume to apply. Initial pricing is based on the starter tier, and it improves as your client portfolio grows. We want to make it accessible to agencies building from a small base." },
      { question: "How does the referral commission work?", answer: "Referral partners earn a commission on the first 12 months of subscription revenue from businesses they refer. The commission rate is documented in the referral partner agreement. Attribution is tracked through a unique referral link." },
    ],
    related: ["/pricing/agency", "/company/about", "/solutions/ai-agency"],
  },
  {
    slug: "careers",
    title: "Careers at Omniweb",
    summary: "Join a team building AI revenue systems for the businesses that need them most.",
    overview: [
      "Omniweb is growing, and we are hiring across engineering, product, customer success, and go-to-market. We are looking for people who are genuinely interested in the problem we are solving — not just the technology, but the real-world impact on the businesses that are using it to grow.",
      "We are a distributed team that works asynchronously by default. Our communication culture is written-first: we document decisions, share context in writing before calling meetings, and treat asynchronous work as the primary mode rather than an accommodation. People who do their best work with focus time and written context tend to thrive here.",
      "We are at an early enough stage that every person on the team has meaningful influence on the product, the culture, and the direction of the company. We are past the stage of constant pivoting and uncertainty — we know what we are building and who we are building it for — but early enough that the team you join now will shape what Omniweb becomes.",
    ],
    problem: "Most AI companies hire aggressively at the wrong time — adding headcount before the product-market fit is clear, creating organizational complexity that slows the team down. Finding the right organization to join is harder than it looks.",
    solution: "Omniweb hires deliberately: for specific, well-defined roles where there is clear demand for the work, at a company with an established customer base, proven unit economics, and a product that is working in the market.",
    valueToIndustry: "Great companies need great teams. When Omniweb hires well and treats people well, the product improves and more businesses benefit. The industry benefits from companies that prioritize culture and output over headcount.",
    valueToUser: "You join a team where your work ships, your ideas are heard, and the product you are building is used by real businesses every day. You grow in a context where quality is valued over quantity.",
    outcome: "Meaningful work on a product that matters to its users. A compensation structure that is fair and transparent. A team culture that takes the work seriously without making work the only thing that matters.",
    features: [
      "Distributed team, async-first communication culture",
      "Competitive compensation with equity participation",
      "Comprehensive benefits including health, dental, and vision",
      "Home office setup budget for remote employees",
      "Annual team gatherings for in-person connection",
      "Clear career progression frameworks",
      "Investment in learning and professional development",
      "Parental leave policy that actually supports families",
    ],
    useCases: [
      "Software engineers looking for a focused, high-ownership role in AI infrastructure",
      "Product designers interested in AI-powered communication products",
      "Customer success managers who want to work closely with real business owners",
      "Sales and go-to-market professionals building pipeline in the SMB AI market",
      "AI researchers interested in applied, production AI systems",
    ],
    howItWorks: [
      "Review the open roles on our careers page. Each listing includes a clear description of the work, the required skills, and what success looks like in the role.",
      "Apply through the listing with a resume and a brief cover note explaining why this specific role at this specific company makes sense for you right now.",
      "Our hiring process is straightforward: an initial conversation with the hiring manager, a practical work sample or technical exercise relevant to the role, and a final conversation with the broader team before an offer.",
    ],
    faq: [
      { question: "Is Omniweb fully remote?", answer: "Yes. We are a distributed team with no physical headquarters that people are expected to work from. Team members work from their home locations across multiple time zones." },
      { question: "What is the interview process like?", answer: "The process typically runs three to four weeks from application to offer for most roles. It involves a hiring manager conversation, a work sample that reflects what the job actually requires, and a team conversation before an offer decision." },
    ],
    related: ["/company/about", "/company/contact", "/company/partners"],
  },
]

export const companyPages: Record<string, PageEntry> = Object.fromEntries(
  companySeeds.map((seed) => [
    seed.slug,
    buildPageEntry({
      sectionLabel: "COMPANY",
      primaryAction: primary,
      secondaryAction: secondary,
      footerEyebrow: "Want to know more about Omniweb?",
      footerTitle: "Talk to a real person on our team.",
      footerDescription: "No sales scripts. No automated sequences. A real conversation about whether Omniweb is right for your business.",
      seed,
      stats: [
        { value: "12+", label: "Industries served" },
        { value: "1000+", label: "Businesses deployed" },
        { value: "24/7", label: "AI availability" },
        { value: "< 2s", label: "Response time" },
      ],
    }),
  ])
) as Record<string, PageEntry>
