import { buildPageEntry, type PageEntry } from "@/lib/marketing-page-data"

const primary = { label: "Talk to Sales", href: "/company/contact" }
const secondary = { label: "Book a Demo", href: "/company/book-demo" }

const companySeeds = [
  {
    slug: "about",
    title: "About Omniweb",
    summary: "Learn how Omniweb is building a multi-tenant AI revenue platform for businesses of every size.",
    problem: "Most websites still act like brochures instead of revenue systems.",
    solution: "Omniweb exists to make AI useful for the actual work of selling, supporting, and following up.",
    valueToIndustry: "The industry gets a company focused on practical AI deployment instead of novelty.",
    valueToUser: "Visitors, customers, and internal teams all get a clearer path to the next step.",
    outcome: "A platform that turns the website into an active business tool.",
    features: ["Mission-driven roadmap", "Practical deployment focus", "Revenue-first design", "Multi-tenant architecture"],
    useCases: ["Investor or stakeholder review", "Customer trust building", "Team alignment"],
    howItWorks: ["Read the mission", "See the platform approach", "Connect with the team"],
    related: ["/company/contact", "/company/partners", "/features/ai-voice-agents"],
  },
  {
    slug: "contact",
    title: "Contact Omniweb",
    summary: "Reach sales, support, or partnerships from a single company hub.",
    problem: "Questions often get scattered across different inboxes and forms.",
    solution: "Omniweb gives visitors a clear contact route so the right team can respond quickly.",
    valueToIndustry: "The company experience becomes simpler and more trustworthy.",
    valueToUser: "People know exactly where to go when they need help or want to buy.",
    outcome: "Faster replies and fewer dropped conversations.",
    features: ["Direct contact paths", "Sales and support routing", "Partnership inquiries", "Fast follow-up"],
    useCases: ["Pre-sales questions", "Implementation help", "Press and partnerships"],
    howItWorks: ["Pick the reason for contact", "Send the request to the right team", "Continue the conversation quickly"],
    related: ["/company/book-demo", "/company/partners", "/company/status"],
  },
  {
    slug: "book-demo",
    title: "Book a Demo",
    summary: "Schedule a tailored walkthrough and see how Omniweb fits your business model in practice.",
    problem: "A generic sales call rarely shows how the platform fits your exact workflow.",
    solution: "A book-demo page helps visitors choose a time and get a focused, use-case-based walkthrough.",
    valueToIndustry: "The company gets a more direct path from curiosity to evaluation.",
    valueToUser: "Buyers can get a real product conversation without back-and-forth scheduling pain.",
    outcome: "More qualified meetings and a better pre-sales experience.",
    features: ["Tailored walkthrough", "Scheduling convenience", "Industry-fit discussion", "Clear next steps"],
    useCases: ["Stakeholder review", "Implementation planning", "Executive evaluation"],
    howItWorks: ["Choose a time", "Share the business context", "See the system in action"],
    related: ["/pricing", "/solutions/ai-agency", "/features/workflow-automation"],
  },
  {
    slug: "partners",
    title: "Partners",
    summary: "See how Omniweb works with agencies, consultants, and ecosystem partners.",
    problem: "Businesses want to know who they can trust to build and support the system.",
    solution: "The partners page highlights collaboration opportunities and the broader ecosystem around Omniweb.",
    valueToIndustry: "The ecosystem gets a clearer place to connect on delivery and growth.",
    valueToUser: "Customers can understand who helps implement, manage, and extend the platform.",
    outcome: "More confidence in the support network around the product.",
    features: ["Agency collaboration", "Integration partners", "Implementation support", "Joint growth paths"],
    useCases: ["Delivery partnerships", "Referral conversations", "Strategic integrations"],
    howItWorks: ["Review the partnership model", "Connect with the team", "Plan the rollout together"],
    related: ["/company/contact", "/solutions/ai-agency", "/resources/integrations"],
  },
  {
    slug: "careers",
    title: "Careers",
    summary: "Join the team building the next generation of AI revenue systems for businesses.",
    problem: "The best products need people who care about outcomes, not just features.",
    solution: "Omniweb careers focus on product, engineering, design, and operations that support a growing platform.",
    valueToIndustry: "The company builds with a longer-term commitment to usable AI for real businesses.",
    valueToUser: "Customers benefit from a team that is aligned on practical, revenue-first work.",
    outcome: "A stronger product and a more cohesive user experience over time.",
    features: ["Mission-driven culture", "Product-focused work", "Cross-functional collaboration", "Growth opportunities"],
    useCases: ["Open roles", "Founding team interest", "Future opportunities"],
    howItWorks: ["Review the role or team fit", "Apply or connect", "Join the work of building the product"],
    related: ["/company/about", "/company/contact", "/company/partners"],
  },
  {
    slug: "privacy",
    title: "Privacy Policy",
    summary: "Review how Omniweb handles data, conversation records, and platform usage information.",
    problem: "Trust depends on clear handling of customer and business data.",
    solution: "The privacy policy explains the way Omniweb thinks about data, usage, and customer protection.",
    valueToIndustry: "The industry gets a clearer model for responsible AI data handling.",
    valueToUser: "Visitors and customers can understand how their information is treated.",
    outcome: "More transparency and easier governance conversations.",
    features: ["Data handling overview", "Usage transparency", "Customer information protections", "Policy clarity"],
    useCases: ["Vendor review", "Compliance review", "Internal security approval"],
    howItWorks: ["Read the policy", "Review the relevant section", "Contact the team with questions"],
    related: ["/company/status", "/company/terms", "/resources/security"],
  },
  {
    slug: "terms",
    title: "Terms of Service",
    summary: "Understand the rules that govern use of the Omniweb platform and services.",
    problem: "Clear service terms are part of a healthy product relationship.",
    solution: "The terms page explains how the platform is used, supported, and governed.",
    valueToIndustry: "The industry gets a more transparent service agreement.",
    valueToUser: "Customers can review expectations before they adopt the platform.",
    outcome: "Fewer surprises and clearer service boundaries.",
    features: ["Service terms", "Usage expectations", "Support clarity", "Platform governance"],
    useCases: ["Purchase review", "Legal approval", "Partner onboarding"],
    howItWorks: ["Read the terms", "Review the obligations", "Proceed with confidence"],
    related: ["/company/privacy", "/company/contact", "/company/status"],
  },
  {
    slug: "status",
    title: "System Status",
    summary: "Check uptime, incidents, and platform health for the Omniweb system.",
    problem: "Teams need a quick way to confirm whether the service is healthy.",
    solution: "The status page gives a simple way to monitor platform conditions and recent incidents.",
    valueToIndustry: "The company gets a more transparent operational story.",
    valueToUser: "Customers can self-serve status checks instead of guessing what is happening.",
    outcome: "Fewer support questions and better confidence during operations.",
    features: ["Uptime visibility", "Incident updates", "Maintenance awareness", "Health overview"],
    useCases: ["Ops monitoring", "Support responses", "Internal validation"],
    howItWorks: ["Review current status", "See recent incidents", "Check maintenance or recovery notes"],
    related: ["/company/contact", "/resources/help-center", "/resources/security"],
  },
] as const

export const companyPages: Record<string, PageEntry> = Object.fromEntries(
  companySeeds.map((seed) => [
    seed.slug,
    buildPageEntry({
      sectionLabel: "COMPANY",
      primaryAction: primary,
      secondaryAction: secondary,
      footerEyebrow: "Want to talk to the team behind Omniweb?",
      footerTitle: "Contact us, book a demo, or review the company story before you decide.",
      footerDescription: "The company pages give visitors a clean path to understand the mission, the people, and the operational details behind the platform.",
      seed,
      stats: [
        { value: "2026", label: "Current build" },
        { value: "1", label: "Company story" },
        { value: "24/7", label: "Support mindset" },
        { value: "0", label: "Guesswork" },
      ],
    }),
  ])
) as Record<string, PageEntry>
