import { buildPageEntry, type PageEntry } from "@/lib/marketing-page-data"

const primary = { label: "Book a Demo", href: "/company/book-demo" }
const secondary = { label: "See Pricing", href: "/pricing" }

const featureSeeds = [
  {
    slug: "ai-voice-agents",
    title: "AI Voice Agents",
    summary: "Answer inbound calls instantly, qualify the caller, and route the right next step without adding more front-desk work.",
    problem: "Missed calls, long hold times, and inconsistent callbacks quietly leak revenue.",
    solution: "Omniweb voice agents answer around the clock, gather context, summarize intent, and hand off to booking or sales when the lead is ready.",
    valueToIndustry: "The industry gets reliable call coverage that scales with demand instead of relying on extra headcount.",
    valueToUser: "Your team spends less time triaging calls and more time closing qualified opportunities.",
    outcome: "Every phone lead gets a real answer, a clear next step, and a clean summary for your team.",
    features: ["After-hours answering", "Lead qualification prompts", "Call summaries and routing", "Callback and booking handoff"],
    useCases: ["Inbound sales teams", "Emergency service desks", "Appointment-driven businesses"],
    howItWorks: ["Pick up the call and identify intent", "Qualify urgency, budget, and fit", "Route the caller into booking or follow-up"],
    related: ["/features/appointment-scheduling", "/features/lead-automation", "/pricing/ai-telephony"],
  },
  {
    slug: "ai-chat-assistants",
    title: "AI Chat Assistants",
    summary: "Turn website traffic into real-time conversations that capture context, answer objections, and move buyers forward.",
    problem: "Visitors bounce when chat is slow, generic, or disconnected from the actual sales process.",
    solution: "Omniweb chat assistants answer instantly, use your business context, and turn interest into booked meetings or captured leads.",
    valueToIndustry: "Website chat becomes a revenue channel, not a passive widget with canned replies.",
    valueToUser: "You get more qualified conversations from the same traffic without having to staff live chat 24/7.",
    outcome: "More visitors stay engaged, get answers quickly, and convert before they leave the page.",
    features: ["Instant live chat", "Objection handling", "Context-aware answers", "Lead capture and routing"],
    useCases: ["High-intent landing pages", "Product and pricing pages", "Support-to-sales handoff"],
    howItWorks: ["Detect visitor intent from the page and question", "Answer with your business knowledge", "Capture the lead and route the handoff"],
    related: ["/features/website-knowledge-base", "/features/workflow-automation", "/solutions/ecommerce"],
  },
  {
    slug: "lead-automation",
    title: "Lead Automation",
    summary: "Score, summarize, route, and follow up with every lead so your pipeline stays organized and fast-moving.",
    problem: "Manual follow-up and data entry create delay, inconsistency, and lost opportunities.",
    solution: "Omniweb turns every conversation into structured lead data, then pushes it into the systems your team already uses.",
    valueToIndustry: "The industry gets a consistent, automated intake engine that removes friction from the buying journey.",
    valueToUser: "Your reps stop copy-pasting notes and can focus on high-value conversations.",
    outcome: "More qualified leads move forward while low-intent leads are automatically filtered and tracked.",
    features: ["Lead scoring", "CRM-ready summaries", "Follow-up triggers", "Automatic routing rules"],
    useCases: ["Multi-step intake forms", "Sales and service teams", "Pipeline prioritization"],
    howItWorks: ["Capture intent and contact details", "Assign a score and route the lead", "Trigger the right follow-up workflow"],
    related: ["/features/crm-integrations", "/features/email-follow-up", "/solutions/professional-services"],
  },
  {
    slug: "multilingual-ai",
    title: "Multilingual AI",
    summary: "Speak to customers in the language they prefer so every buyer gets a smoother, more local experience.",
    problem: "Language friction causes visitors to abandon forms, hang up, or miss key details during intake.",
    solution: "Omniweb can respond in multiple languages and keep the conversation moving without forcing a human translator.",
    valueToIndustry: "The industry gains a broader reach and a more inclusive front door for sales and support.",
    valueToUser: "Your team can serve more customers without rebuilding the experience for every region.",
    outcome: "International and multilingual buyers get fast, accurate, and natural interactions.",
    features: ["Multi-language chat", "Voice and text support", "Localized lead capture", "Language-aware routing"],
    useCases: ["Tourism and hospitality", "Regional service businesses", "Global ecommerce"],
    howItWorks: ["Detect or select the customer language", "Respond with localized context", "Route the lead to the right team"],
    related: ["/features/ai-chat-assistants", "/features/website-knowledge-base", "/solutions/ecommerce"],
  },
  {
    slug: "appointment-scheduling",
    title: "Appointment Scheduling",
    summary: "Move from interest to a booked time slot with less back-and-forth and fewer drop-offs.",
    problem: "Scheduling friction delays conversions and pushes buyers back into the weeds.",
    solution: "Omniweb asks the right questions, checks readiness, and helps the visitor lock in a time that works.",
    valueToIndustry: "The industry gets a repeatable booking workflow that fits sales, intake, and service operations.",
    valueToUser: "Your customers get an easier path to a call, consultation, or visit.",
    outcome: "More conversations end with a confirmed appointment instead of an abandoned thread.",
    features: ["Calendar-friendly booking", "Qualification before scheduling", "Automatic reminders", "Timezone-aware coordination"],
    useCases: ["Consultations", "Service appointments", "High-ticket sales calls"],
    howItWorks: ["Qualify the visitor first", "Find the right time window", "Send confirmations and reminders"],
    related: ["/features/lead-automation", "/solutions/professional-services", "/pricing/combo"],
  },
  {
    slug: "crm-integrations",
    title: "CRM Integrations",
    summary: "Push contact details, notes, and qualification data into the CRM your team already relies on.",
    problem: "Disconnected systems create duplicate work and cause valuable lead details to disappear.",
    solution: "Omniweb integrates with your workflow so every conversation creates a usable record for sales and follow-up.",
    valueToIndustry: "The industry gets cleaner handoffs and a better source of truth for revenue conversations.",
    valueToUser: "Your team sees the right lead data at the right time without manual copying.",
    outcome: "Nothing falls through the cracks between the website, the conversation, and the CRM.",
    features: ["CRM-ready lead records", "Integration-friendly webhooks", "Field mapping support", "Conversation summaries"],
    useCases: ["GoHighLevel workflows", "Salesforce or HubSpot handoff", "Custom pipeline syncing"],
    howItWorks: ["Collect the lead context", "Map it to your CRM fields", "Keep follow-up data synchronized"],
    related: ["/features/workflow-automation", "/features/email-follow-up", "/pricing/enterprise"],
  },
  {
    slug: "email-follow-up",
    title: "Email Follow-Up",
    summary: "Automate the right follow-up message after the conversation ends so interest stays warm.",
    problem: "Manual follow-up is easy to delay and hard to scale when lead volume increases.",
    solution: "Omniweb sends structured follow-up based on the conversation outcome, the lead type, and the next best action.",
    valueToIndustry: "The industry gets a more dependable nurture layer that improves response speed.",
    valueToUser: "Your team can stay consistent without writing every follow-up from scratch.",
    outcome: "Leads stay engaged after the first touch, which increases booked calls and closed opportunities.",
    features: ["Triggered follow-up", "Lead-specific messaging", "Manual review options", "Conversion-friendly timing"],
    useCases: ["Quote requests", "Consultation follow-up", "Abandoned chat recovery"],
    howItWorks: ["Capture the reason for contact", "Choose the right follow-up path", "Send the message automatically"],
    related: ["/features/lead-automation", "/solutions/contractors", "/pricing/combo"],
  },
  {
    slug: "analytics-reporting",
    title: "Analytics & Reporting",
    summary: "See how your AI system performs across conversations, lead quality, bookings, and response speed.",
    problem: "Without good reporting, teams cannot tell which conversations are driving revenue.",
    solution: "Omniweb gives you a clean view of conversation outcomes, user behavior, and workflow performance.",
    valueToIndustry: "The industry gets a measurement layer that links AI activity to actual business outcomes.",
    valueToUser: "Your team can make better decisions without stitching together spreadsheets and dashboards.",
    outcome: "You know what converts, what needs tuning, and where the revenue leaks are hiding.",
    features: ["Conversation summaries", "Lead quality insights", "Response-time tracking", "Outcome reporting"],
    useCases: ["Weekly performance reviews", "Campaign optimization", "Sales forecasting support"],
    howItWorks: ["Log every interaction", "Summarize the result", "Review the patterns and improve the workflow"],
    related: ["/features/lead-automation", "/resources/compare", "/solutions/ai-agency"],
  },
  {
    slug: "website-knowledge-base",
    title: "Website Knowledge Base",
    summary: "Let Omniweb answer from your site content so every response sounds like it was written by your business.",
    problem: "Visitors ask questions the page should have answered, but static content cannot respond in real time.",
    solution: "Omniweb reads your website knowledge, then uses it to answer questions accurately and consistently.",
    valueToIndustry: "The industry gets a smarter front end that turns existing content into a live revenue asset.",
    valueToUser: "Your team can rely on the system to answer from the source material already on the site.",
    outcome: "More questions get answered instantly, and fewer buyers leave because they could not find the right page.",
    features: ["Site-aware answers", "FAQ and page context", "Brand-safe responses", "Continuous content reuse"],
    useCases: ["Service pages", "Product detail pages", "Policy and FAQ support"],
    howItWorks: ["Ingest site content", "Use it during the conversation", "Keep the knowledge up to date"],
    related: ["/features/ai-chat-assistants", "/resources/docs", "/resources/guides"],
  },
  {
    slug: "video-presenter",
    title: "Video Presenter",
    summary: "Use a guided video presentation to explain offers, educate visitors, and keep people engaged longer.",
    problem: "Some buyers need a visual explanation before they are ready to convert.",
    solution: "Omniweb can pair your message with a polished video-presenter experience that keeps attention on the offer.",
    valueToIndustry: "The industry gets a more engaging sales narrative that combines AI interaction with visual storytelling.",
    valueToUser: "Your team gets a better way to walk visitors through value without being live every time.",
    outcome: "Visitors understand the offer faster and are more likely to take the next step.",
    features: ["Guided video experiences", "Message-driven storytelling", "Attention-friendly layout", "Conversion CTAs"],
    useCases: ["Product launch pages", "Founder story pages", "High-consideration offers"],
    howItWorks: ["Show the right video at the right moment", "Pair it with supporting copy", "Invite the visitor to take action"],
    related: ["/features/ai-chat-assistants", "/resources/blog", "/solutions/ecommerce"],
  },
  {
    slug: "workflow-automation",
    title: "Workflow Automation",
    summary: "Connect the front-end conversation to the systems that execute the follow-up and routing work.",
    problem: "Without automation, every lead needs manual triage before it can move forward.",
    solution: "Omniweb triggers the right sequence of tasks, notifications, and updates based on what the customer does.",
    valueToIndustry: "The industry gets a workflow layer that compresses response time and improves consistency.",
    valueToUser: "Your team spends less time doing repetitive admin and more time on real opportunities.",
    outcome: "The whole system moves faster because the next action happens automatically.",
    features: ["Automated handoffs", "Trigger-based tasks", "Cross-system coordination", "Lead-status updates"],
    useCases: ["Sales handoff", "Support escalation", "Pipeline follow-through"],
    howItWorks: ["Capture the event or intent", "Trigger the right action", "Keep every system in sync"],
    related: ["/features/lead-automation", "/features/crm-integrations", "/solutions/ai-agency"],
  },
] as const

export const featurePages: Record<string, PageEntry> = Object.fromEntries(
  featureSeeds.map((seed) => [
    seed.slug,
    buildPageEntry({
      sectionLabel: "FEATURES",
      primaryAction: primary,
      secondaryAction: secondary,
      footerEyebrow: "Ready to turn a feature into a live system?",
      footerTitle: "Install the capability on your website and start qualifying more revenue.",
      footerDescription: "Each feature page connects you to the same Omniweb engine — voice, chat, automation, and measurable outcomes.",
      seed,
      stats: [
        { value: "24/7", label: "Coverage" },
        { value: "< 2s", label: "Response" },
        { value: "1", label: "Platform" },
        { value: "100%", label: "Connected system" },
      ],
    }),
  ])
) as Record<string, PageEntry>
