import { buildPageEntry, type PageEntry } from "@/lib/marketing-page-data"

const primary = { label: "Book a Demo", href: "/company/book-demo" }
const secondary = { label: "See Pricing", href: "/pricing" }

const featureSeeds = [
  {
    slug: "ai-voice-agents",
    title: "AI Voice Agents",
    summary: "Answer inbound calls instantly, qualify the caller, and route the right next step without adding more front-desk work.",
    overview: [
      "Every missed call is a missed opportunity. Whether it is a prospect calling after hours, a customer asking a time-sensitive question, or a repeat buyer trying to change an order, the moment someone reaches voicemail instead of a live answer, a portion of your revenue pipeline quietly dissolves. The Omniweb AI Voice Agent changes that equation permanently.",
      "Our voice agent picks up every inbound call in under two seconds, identifies the reason for the call, and responds in natural conversation. It does not read a script in a robotic tone — it adapts to what the caller is actually saying, uses your business context to give accurate answers, and takes action on what comes next: booking an appointment, capturing a lead, routing to a live rep, or sending a follow-up message.",
      "For teams already stretched thin at the front desk, this means the phones are always covered without adding headcount. For growing businesses that receive calls from multiple channels — ads, organic search, referrals, past customers — it means every lead is treated with the same speed and professionalism, regardless of when they call or how busy the team is.",
      "The Omniweb voice agent integrates with your scheduling tools, CRM, and follow-up workflows so that the conversation does not end at the phone. Qualification notes, caller details, intent scores, and next steps flow directly into your pipeline, ready for your team to act on the opportunities that matter most.",
    ],
    problem: "Most businesses lose a significant portion of their leads simply because nobody answered. A caller who gets voicemail will try a competitor within minutes. After-hours calls go unanswered. During busy periods the phone rings while the team is occupied. Every one of these moments is a direct revenue leak that stacks up over time.",
    solution: "Omniweb's AI Voice Agent is permanently on, answers every call in under two seconds, and responds as a knowledgeable extension of your business. It qualifies urgency and intent, answers product and service questions using your own knowledge base, and routes the caller into the right next step — booking, callback queue, or live handoff — automatically.",
    valueToIndustry: "The broader market benefits from a reliable, scalable alternative to understaffed front desks. Businesses that previously could not compete on responsiveness now have a consistent answer to every inquiry, which raises the overall quality of customer experience across industries that depend on phone-based intake.",
    valueToUser: "Your team stops losing time to calls that could be handled automatically and stops losing revenue to calls that go unanswered. Sales reps focus on qualified callbacks. Service staff focus on booked appointments. The AI handles everything that comes before those conversations.",
    outcome: "Every caller gets a real, immediate answer. Qualified leads flow cleanly into the pipeline with all the context your team needs. Bookings increase. Response time drops to near-zero. The revenue that was previously leaking through missed calls gets captured instead.",
    features: [
      "24/7 inbound call answering with sub-2-second pickup",
      "Natural language conversation using your business context",
      "Multi-step caller qualification with intent scoring",
      "Appointment and callback booking without human involvement",
      "CRM-ready call summaries delivered after each call",
      "Voicemail fallback and callback triggers for edge cases",
      "Escalation routing to live staff when needed",
      "Support for multiple phone lines and departments",
    ],
    useCases: [
      "Service businesses handling quote requests and appointment calls",
      "Sales teams qualifying inbound leads before a rep takes over",
      "Healthcare and professional offices handling intake and scheduling",
      "E-commerce support lines answering order and delivery questions",
      "After-hours coverage for businesses that cannot staff evenings and weekends",
    ],
    howItWorks: [
      "The AI answers the call, greets the caller by context (which number they called, what page or ad they came from), and opens with the right first question to identify intent.",
      "The conversation unfolds naturally. The AI listens, responds to what the caller actually says, handles follow-up questions, and uses your business data — pricing, services, policies, availability — to give accurate answers.",
      "The call ends with a clear next step: a booked appointment, a captured lead sent to your CRM, a routed transfer to a live rep, or an automated follow-up message with all the relevant context attached.",
    ],
    faq: [
      { question: "How quickly does the AI answer?", answer: "The Omniweb voice agent picks up in under two seconds. There is no hold music, no menu tree to navigate. The caller is in a conversation almost immediately." },
      { question: "Can it handle calls for multiple locations or departments?", answer: "Yes. You can configure different scripts, routing logic, and knowledge bases for each phone number or department. The AI knows which number was called and responds accordingly." },
      { question: "What happens when the caller needs a real person?", answer: "The agent recognizes escalation signals — frustration, complex requests, high-value intent — and transfers the call to the appropriate staff member with a live summary of what was discussed." },
      { question: "Does it work with my existing CRM?", answer: "Omniweb integrates with most major CRM platforms and uses webhooks to push call data, lead records, and summaries wherever your team needs them." },
    ],
    related: ["/features/appointment-scheduling", "/features/lead-automation", "/pricing/ai-telephony"],
  },
  {
    slug: "ai-chat-assistants",
    title: "AI Chat Assistants",
    summary: "Turn website traffic into real-time conversations that capture context, answer objections, and move buyers forward.",
    overview: [
      "Your website gets traffic every day — but most of that traffic leaves without converting. Not because the product is wrong or the price is too high, but because the visitor had a question they could not answer on their own. They wanted to know if the service covers their area, whether the product works with their setup, or how long the process takes — and there was no one to ask.",
      "Omniweb's AI Chat Assistant fixes that gap. It sits on your website, learns your business from the inside out, and engages visitors in the moment they need answers. Not with a generic chatbot that fires a pre-written greeting and routes everything to email — but with a real conversation that knows your pricing, your services, your policies, and your customers.",
      "The difference between a visitor who converts and one who bounces is often a single answered question. The Omniweb chat assistant answers those questions instantly, any time of day, and turns hesitant browsers into qualified conversations your team can close.",
      "Every chat interaction generates structured data — what the visitor asked, what they cared about, what objections came up, and what they agreed to next. That data flows directly into your pipeline so your team always knows the full context before they reach out.",
    ],
    problem: "Generic chat widgets do not convert because they respond too slowly, too generically, or not at all. Visitors who bounce rarely return. The window of attention on a high-intent page is short — usually under three minutes — and if the chat assistant cannot answer the actual question, the visitor leaves and takes their budget with them.",
    solution: "Omniweb's AI Chat Assistant responds instantly with context-aware answers drawn from your business knowledge. It handles objections, qualifies the visitor's needs, captures contact details, and routes the right leads to your team — all without any manual involvement from your staff.",
    valueToIndustry: "The broader impact is a shift from passive websites to active revenue channels. Businesses that deploy intelligent chat convert more of the traffic they already have, which improves the return on every marketing dollar spent.",
    valueToUser: "You get qualified conversations from visitors who would have otherwise bounced. Your team gets leads with context — not just a name and email, but a full picture of what the visitor wanted and what was discussed.",
    outcome: "Bounce rates drop. Lead capture rates increase. Visitors get the answers they need to feel confident, and your pipeline fills with higher-quality opportunities from the same traffic you were already paying for.",
    features: [
      "Instant response with no loading delay or wait states",
      "Business-aware answers drawn from your knowledge base",
      "Objection handling and follow-up question management",
      "Lead capture with name, email, phone, and intent classification",
      "Handoff to live staff with full conversation summary",
      "Proactive chat triggers based on page, time-on-site, and scroll depth",
      "Mobile-optimized and embeddable on any page",
      "Multi-language support for diverse audiences",
    ],
    useCases: [
      "High-intent landing pages where visitors have specific questions before converting",
      "Pricing pages where objections need to be handled in real time",
      "Product pages where shoppers need guidance to make a decision",
      "Service sites where scope, availability, and pricing are common questions",
      "B2B websites where buyers are evaluating fit before requesting a demo",
    ],
    howItWorks: [
      "The chat assistant loads on the page and watches for engagement signals — time on page, scroll depth, exit intent — to decide when to open proactively or wait for the visitor to initiate.",
      "When a conversation starts, the AI draws from your knowledge base to answer the specific question, handles follow-ups, and moves the visitor toward a conversion action — booking, form fill, or phone call.",
      "At the end of every conversation, a structured summary is pushed to your CRM, your email, or your dashboard with the visitor's contact details, intent classification, and the full transcript.",
    ],
    faq: [
      { question: "How does the AI learn my business?", answer: "Omniweb ingests your website content, product descriptions, service pages, FAQs, and any additional knowledge documents you provide. The assistant uses this to give accurate, brand-consistent answers." },
      { question: "Can it handle multi-step qualification flows?", answer: "Yes. You can configure multi-step question sequences for different page types or visitor intents. The AI follows the logic while still responding naturally to off-script questions." },
      { question: "What happens when the visitor is ready to buy or book?", answer: "The assistant can route directly to a booking form, a calendar link, a phone number, or a live handoff to a sales rep — depending on what you configure for each flow." },
      { question: "Will it work on my existing website?", answer: "Omniweb chat embeds with a single script tag and works on any website platform — WordPress, Shopify, Webflow, custom HTML, or Next.js." },
    ],
    related: ["/features/website-knowledge-base", "/features/workflow-automation", "/solutions/ecommerce"],
  },
  {
    slug: "lead-automation",
    title: "Lead Automation",
    summary: "Score, summarize, route, and follow up with every lead so your pipeline stays organized and fast-moving.",
    overview: [
      "A lead that is not acted on within the first five minutes is five times less likely to convert than one that gets an immediate response. Most businesses know this — and most businesses still miss that window because someone has to manually review the inquiry, figure out who it belongs to, log it in the CRM, and send a follow-up message. By the time all of that happens, the lead has already moved on.",
      "Omniweb's Lead Automation engine eliminates that lag entirely. The moment a conversation ends — whether it started on voice, chat, or a form — the AI generates a structured lead record, assigns a qualification score, routes the lead to the right team member, and triggers the first follow-up automatically. All of it happens before the human ever needs to get involved.",
      "The result is a pipeline that moves at the speed of the conversation rather than the speed of manual admin. Every lead gets the same consistent first response, every lead is logged with the same structure, and every lead gets a follow-up at the optimal moment — whether that is five minutes after the conversation or five days later based on the sequence you configure.",
    ],
    problem: "Manual lead management creates delay, inconsistency, and missed opportunities. Reps who are responsible for their own follow-up get buried during busy periods and let promising leads cool off. CRM entries are incomplete or never created. High-intent leads and low-intent browsing get the same slow response.",
    solution: "Omniweb automates every step between the first conversation and the first human touchpoint. Lead scoring, CRM entry, routing, and follow-up sequences all run automatically based on what the AI learned during the conversation — so your team only touches the opportunities that are ready to close.",
    valueToIndustry: "The overall market benefits from a tighter connection between marketing spend and revenue. When leads are acted on consistently and immediately, conversion rates improve across the board — which means businesses get more from the same acquisition costs.",
    valueToUser: "Your reps spend their time on qualified, ready-to-close conversations instead of triage. Nothing falls through the cracks. The pipeline is always current. Follow-up is never forgotten.",
    outcome: "Response time collapses from hours to seconds. Lead-to-meeting conversion rates increase because follow-up is consistent and timely. Reps close more because they spend time talking to real buyers instead of managing spreadsheets.",
    features: [
      "Automatic lead scoring based on intent, urgency, and qualification data",
      "CRM-ready records with conversation transcript and structured fields",
      "Intelligent routing to the right rep, team, or workflow",
      "Triggered follow-up sequences — email, SMS, or both",
      "Lead deduplication and enrichment",
      "Priority flagging for high-intent leads",
      "Full audit trail from first touch to conversion",
      "Reporting on conversion rates by lead source and score tier",
    ],
    useCases: [
      "Sales teams that receive more leads than they can manually triage",
      "Service businesses qualifying urgency before dispatching a technician",
      "Agencies managing leads across multiple client accounts",
      "E-commerce brands recovering abandoned cart and browse intent signals",
      "Professional services firms screening prospects before consultation",
    ],
    howItWorks: [
      "Every conversation — voice, chat, or form — is analyzed by the AI at close. Intent signals, qualification answers, urgency markers, and contact details are extracted and structured automatically.",
      "The system scores the lead, assigns it to the correct routing destination, and logs a complete record in your CRM with all the context your team needs to continue the conversation.",
      "Follow-up sequences fire on the schedule you configure — immediate email confirmation, next-day check-in, and weekly nurture — so the lead stays engaged until they are ready to move forward.",
    ],
    faq: [
      { question: "How does the lead scoring work?", answer: "Omniweb assigns scores based on the qualification answers collected during the conversation — budget range, timeline, urgency, fit with your service, and engagement level. You can customize the scoring criteria for your market." },
      { question: "Can I configure different routing rules for different lead types?", answer: "Yes. You can create routing rules based on score, service type, location, or any other field captured in the conversation. High-urgency leads can be routed directly to senior reps while routine inquiries go into a standard queue." },
      { question: "How long does the follow-up sequence run?", answer: "You configure the duration and frequency. Most customers run a 7–14 day sequence with daily or every-other-day touchpoints. The sequence stops automatically when the lead responds or converts." },
    ],
    related: ["/features/crm-integrations", "/features/email-follow-up", "/solutions/professional-services"],
  },
  {
    slug: "multilingual-ai",
    title: "Multilingual AI",
    summary: "Speak to customers in the language they prefer so every buyer gets a smoother, more local experience.",
    overview: [
      "Language is one of the most underestimated conversion barriers in business. A visitor who cannot understand your offering clearly is unlikely to take action — and a customer who has to struggle to communicate their needs is likely to find a provider who makes it easier. For businesses serving multilingual markets, the gap between the language you communicate in and the language your customer thinks in is a direct cost.",
      "Omniweb's Multilingual AI removes that cost. Whether you are a home services business serving a Spanish-speaking community, a healthcare provider with a diverse patient base, or a global e-commerce brand, the same AI system that handles your English conversations handles your multilingual ones — with the same context, the same knowledge, and the same conversion focus.",
      "There is no need to build separate chat flows or hire bilingual staff for coverage. The AI detects the language of the visitor or caller and responds in kind, drawing from your business knowledge regardless of the language the question was asked in.",
    ],
    problem: "Language friction causes visitors to abandon forms, callers to hang up, and buyers to move on to providers who speak their language. Building separate language experiences for each market is expensive and hard to maintain. And relying on translation tools that break the conversation flow is a poor substitute for genuine comprehension.",
    solution: "Omniweb handles conversations in multiple languages natively, using the same business knowledge and qualification logic regardless of what language the customer uses. Setup does not require separate workflows for each language — the system adapts in real time.",
    valueToIndustry: "Multilingual AI democratizes quality customer communication for businesses that serve diverse communities. Industries from healthcare to legal services to retail can now reach more of their addressable market without proportionally increasing their communication costs.",
    valueToUser: "You serve more customers, in more markets, with the same AI system. No extra headcount, no translation overhead, no separate workflows to maintain.",
    outcome: "International and multilingual buyers get a natural, respectful experience in their preferred language. Lead capture rates in multilingual markets improve. Customer satisfaction increases because communication barriers are removed.",
    features: [
      "Real-time language detection from voice or text",
      "Natural conversation in the detected language without code-switching",
      "Business knowledge accessed in any supported language",
      "Lead capture and CRM records written in a single standardized language",
      "Language-aware routing to bilingual staff when needed",
      "Support for major global languages and regional variants",
    ],
    useCases: [
      "Service businesses in metropolitan areas with diverse customer bases",
      "Healthcare providers serving multilingual patient populations",
      "E-commerce brands selling in multiple countries",
      "Legal and professional services with international clients",
      "Hospitality and tourism businesses serving international visitors",
    ],
    howItWorks: [
      "When a visitor initiates a chat or a caller speaks, the AI detects the language immediately and switches its response to match — no menu selection required.",
      "The conversation continues in the customer's language, with full access to your business knowledge base. Questions, qualifications, and objection handling all work the same way regardless of language.",
      "Lead records are created in your standardized language format so your team can work from a consistent dataset even when leads came in from multiple language contexts.",
    ],
    faq: [
      { question: "Which languages are supported?", answer: "Omniweb supports the major global languages including Spanish, French, German, Portuguese, Italian, Japanese, Mandarin, and many more. Contact us for the full current list." },
      { question: "Do I need to maintain separate knowledge bases for each language?", answer: "No. Omniweb translates your knowledge base dynamically. You maintain one source of truth and the AI handles the language layer automatically." },
      { question: "Can multilingual conversations still feed the same CRM workflow?", answer: "Yes. Lead records, scoring, routing, and follow-up sequences work identically regardless of the language the conversation happened in." },
    ],
    related: ["/features/ai-chat-assistants", "/features/website-knowledge-base", "/solutions/ecommerce"],
  },
  {
    slug: "appointment-scheduling",
    title: "Appointment Scheduling",
    summary: "Move from interest to a booked time slot with less back-and-forth and fewer drop-offs.",
    overview: [
      "Scheduling friction is one of the most consistent conversion killers in service and sales businesses. A prospect who is interested today but cannot easily book a call, consultation, or visit will often never return. The more steps between 'I want to talk' and 'I'm booked,' the more people drop off — and most of those drop-offs are preventable.",
      "Omniweb's appointment scheduling capability sits inside the AI conversation itself. Instead of directing a visitor to a separate booking page and hoping they complete the process, the AI handles the scheduling inline — asking the right qualifying questions first, confirming availability, sending the booking confirmation, and adding the appointment to your calendar — all within the same conversation flow.",
      "For sales teams, this means demo requests turn into confirmed calls in seconds. For service businesses, it means quote requests turn into site visits without phone tag. For healthcare and professional services, it means new patient or client intake flows directly into a scheduled appointment with all the context pre-captured.",
    ],
    problem: "Most scheduling flows require too many steps and too much trust from a visitor who is still early in their decision. Sending a Calendly link as the first response to an inquiry loses people who are not yet committed enough to hunt for a time slot. Back-and-forth email scheduling burns hours and lets interest cool.",
    solution: "Omniweb embeds scheduling directly into the AI conversation. Qualification happens first, then the AI presents available times, confirms the appointment, and sends reminders automatically — all without the visitor leaving the chat or the business picking up the phone.",
    valueToIndustry: "Embedding scheduling in AI conversations is a structural improvement to how service businesses convert leads. It removes the most common drop-off point in the funnel and replaces it with a seamless transition from interest to commitment.",
    valueToUser: "Your team stops spending time on scheduling coordination and gets focused on the conversations that follow confirmed appointments. Your calendar fills with qualified, committed meetings instead of vague 'let's connect' requests.",
    outcome: "Appointment show rates increase because booking is easier and reminders are automatic. No-shows drop because the commitment is confirmed clearly in the conversation. Your team spends more of their time on billable or revenue-generating work.",
    features: [
      "Inline scheduling within the AI chat or voice conversation",
      "Qualification-first flow so only serious prospects book time",
      "Real-time calendar availability checking",
      "Automatic confirmation emails and SMS reminders",
      "Rescheduling and cancellation handling",
      "Timezone-aware booking for distributed teams",
      "Integration with Google Calendar, Outlook, and booking platforms",
      "Custom intake questions collected before the appointment",
    ],
    useCases: [
      "Sales teams booking demo and discovery calls from inbound traffic",
      "Service businesses converting quote requests into site visits",
      "Healthcare practices scheduling new patient intake appointments",
      "Consultants and advisors booking initial consultations",
      "Home services companies scheduling estimates and service calls",
    ],
    howItWorks: [
      "The AI qualifies the visitor first — confirming they are a genuine fit for the service or conversation — before presenting scheduling options. This prevents calendar pollution from low-quality bookings.",
      "Available time slots are presented based on your real-time calendar, and the visitor selects the time that works for them. The AI confirms the booking, collects any remaining intake information, and sends the calendar invite.",
      "Automated reminders go out the day before and the morning of the appointment. If the visitor needs to reschedule, they can do so through the reminder link without involving your team.",
    ],
    faq: [
      { question: "Does it work with my existing calendar?", answer: "Yes. Omniweb connects to Google Calendar, Outlook/Office 365, and most major scheduling platforms. Availability is checked in real time so there are no double-bookings." },
      { question: "Can I add custom questions before the appointment is confirmed?", answer: "Yes. You can configure intake questions that must be answered before the booking is accepted. The answers flow into your CRM alongside the appointment record." },
      { question: "What happens if someone needs to cancel?", answer: "The reminder messages include a rescheduling link. Cancellations open the time slot back up automatically. You receive a notification so you can adjust your day." },
    ],
    related: ["/features/lead-automation", "/solutions/professional-services", "/pricing/combo"],
  },
  {
    slug: "crm-integrations",
    title: "CRM Integrations",
    summary: "Push contact details, notes, and qualification data into the CRM your team already relies on.",
    overview: [
      "A CRM is only as useful as the data inside it — and most CRM data is either incomplete, delayed, or never entered at all. Reps who are responsible for their own data entry tend to log the easy fields and skip the context that actually matters: what the prospect said about budget, what their timeline is, what objection came up, and what they agreed to as a next step.",
      "Omniweb solves the data quality problem at the source. Every conversation the AI has — voice, chat, or form — is automatically converted into a complete, structured CRM record. The contact's name, email, phone, and company are captured. The qualification answers are logged. The intent score is assigned. The conversation transcript is attached. And all of it is pushed to your CRM the moment the conversation ends.",
      "The result is a CRM that actually reflects what is happening in your pipeline — in real time, with consistent data quality across every lead, regardless of which channel they came from or which AI conversation they had.",
    ],
    problem: "Disconnected conversation and CRM systems create gaps that cost deals. Reps who have to manually translate a chat transcript into CRM fields lose time and miss details. Leads that never make it into the CRM cannot be followed up on. And without consistent data, pipeline reporting is always guesswork.",
    solution: "Omniweb integrates directly with your CRM so every conversation creates a complete, structured record automatically. No manual entry, no missing fields, no delay. The data is there when your team needs it.",
    valueToIndustry: "Reliable conversation-to-CRM data gives the whole market better pipeline visibility. When every lead is logged consistently, forecasting becomes more accurate, coaching becomes more targeted, and conversion optimization becomes data-driven rather than intuition-based.",
    valueToUser: "Your team works from a CRM that is always current and always complete. They can jump into a follow-up call knowing exactly what was discussed and what was promised, without having to search through chat logs or hope that someone took good notes.",
    outcome: "Higher data quality across your pipeline. Faster follow-up because context is always available. Better reporting because every lead is tracked from first touch. More closed deals because reps have the information they need to personalize every conversation.",
    features: [
      "Automatic CRM record creation after every conversation",
      "Full qualification data mapped to CRM fields",
      "Conversation transcript and AI summary attached to each record",
      "Intent score and lead tier written as CRM properties",
      "Custom field mapping to match your existing CRM structure",
      "Duplicate detection and record merging",
      "Real-time sync — no batch delays or manual exports",
      "Support for GoHighLevel, HubSpot, Salesforce, Zoho, and custom webhooks",
    ],
    useCases: [
      "Sales teams that need complete lead records for follow-up without manual entry",
      "Service businesses logging job requests and qualification details",
      "Agencies managing lead data across multiple client CRM instances",
      "E-commerce brands connecting chat conversations to customer records",
      "Professional services firms capturing intake context before consultations",
    ],
    howItWorks: [
      "After each conversation, the AI extracts structured data — contact fields, qualification answers, intent signals, and conversation summary — and maps them to your CRM's field structure.",
      "The record is created or updated in your CRM within seconds of the conversation ending. Your team receives a notification if the lead meets a priority threshold.",
      "The full transcript and AI-generated summary are attached to the record so any team member can read the full context at a glance before making their first call.",
    ],
    faq: [
      { question: "Which CRM platforms does Omniweb connect to?", answer: "We have native integrations with GoHighLevel, HubSpot, Salesforce, Zoho CRM, and Pipedrive. For other platforms, we provide webhook and API support for custom integration." },
      { question: "Can I customize which fields are mapped from the conversation?", answer: "Yes. You define which conversation data maps to which CRM fields during setup. You can add custom properties and configure conditional mapping based on lead type or source." },
      { question: "Does it work if I change my CRM later?", answer: "Yes. The integration layer is configured separately from the conversation logic, so switching CRMs requires only updating the connection settings — not rebuilding your conversation flows." },
    ],
    related: ["/features/workflow-automation", "/features/email-follow-up", "/pricing/enterprise"],
  },
  {
    slug: "email-follow-up",
    title: "Email Follow-Up",
    summary: "Automate the right follow-up message after the conversation ends so interest stays warm.",
    overview: [
      "The follow-up is where most revenue is won or lost. A buyer who had a positive first interaction will often convert if they receive a timely, relevant message that continues the conversation — and will often move on if they hear nothing. Most businesses understand this in theory but struggle to execute it consistently at scale. When lead volume is high or the team is stretched, follow-up becomes reactive or forgotten entirely.",
      "Omniweb's email follow-up automation takes the execution off your team's plate. Every conversation ends with a follow-up sequence that is tailored to what was discussed: the service the lead asked about, the objection they raised, the timeline they mentioned, and the next step they agreed to. The first message goes out within minutes of the conversation ending. Subsequent messages follow the cadence you configure, stopping automatically when the lead responds or converts.",
      "The key difference from generic email tools is that Omniweb's follow-up is built from the conversation context. The message references what the lead actually said, not a template that could apply to anyone. That specificity is what makes recipients open, respond, and convert at higher rates.",
    ],
    problem: "Generic follow-up emails get ignored. Late follow-up loses leads to competitors. Manual follow-up is inconsistent and hard to scale. Teams that rely on individual reps to manage their own follow-up create gaps wherever attention is stretched.",
    solution: "Omniweb generates follow-up messages from the actual conversation content and sends them on the schedule you define. The lead receives a message that is relevant, timely, and specific to what they discussed — automatically, without any manual involvement.",
    valueToIndustry: "The market benefits from a higher standard of post-conversation engagement. When businesses follow up well and consistently, buyer trust increases and sales cycles shorten — which is good for everyone in the ecosystem.",
    valueToUser: "Your pipeline stays warm without requiring your team to manage it manually. Leads that went quiet come back. The next-day follow-up that always slips gets sent on time, every time.",
    outcome: "More leads respond to follow-up. Sales cycles shorten because the next conversation happens faster. Revenue that would have slipped away due to inaction gets captured instead.",
    features: [
      "Conversation-triggered follow-up sequences",
      "Context-aware messaging based on what was discussed",
      "Configurable send cadence — hours, days, or weeks",
      "A/B testing for subject lines and message content",
      "Automatic sequence termination on response or conversion",
      "Lead-specific personalization drawn from qualification data",
      "Multi-step sequences with branching logic",
      "Full open, click, and reply tracking",
    ],
    useCases: [
      "Sales teams nurturing leads that did not convert on first contact",
      "Service businesses following up on quote requests",
      "E-commerce brands re-engaging visitors who browsed but did not buy",
      "Professional services firms maintaining contact with prospective clients",
      "Agencies following up on consultation requests for multiple clients",
    ],
    howItWorks: [
      "When a conversation ends, the AI tags the lead with the relevant context: service interest, objection type, timeline, urgency, and agreed next step. This context determines which follow-up sequence activates.",
      "The first email goes out within the configured time window — often within 30 minutes of the conversation. The message references the specific conversation, the lead's name, and the next step that was discussed.",
      "Each subsequent message in the sequence adapts based on engagement. Unopened emails may trigger a different subject line. Replies immediately move the lead out of automation and into your direct inbox for human follow-up.",
    ],
    faq: [
      { question: "Can I customize the email templates?", answer: "Yes. You have full control over the email content, tone, and structure. Omniweb provides templates that perform well as a starting point, and you can edit them to match your brand voice." },
      { question: "What triggers a follow-up sequence?", answer: "Follow-up sequences are triggered by conversation outcomes — a completed chat, a voice call, a form submission, or a specific qualification result. You define which outcomes trigger which sequences." },
      { question: "Does it also send SMS follow-ups?", answer: "Yes. Omniweb supports combined email and SMS follow-up sequences. SMS messages can be configured to send at different points in the cadence, and opt-out is handled automatically." },
    ],
    related: ["/features/lead-automation", "/solutions/contractors", "/pricing/combo"],
  },
  {
    slug: "analytics-reporting",
    title: "Analytics & Reporting",
    summary: "See how your AI system performs across conversations, lead quality, bookings, and response speed.",
    overview: [
      "If you cannot measure it, you cannot improve it — and most businesses running AI systems are flying partially blind. They know calls are getting answered and chats are being handled, but they do not have a clear picture of which conversations are driving revenue, which qualification flows are underperforming, or where leads are dropping off in the funnel.",
      "Omniweb's analytics and reporting layer gives you that picture. Every conversation, every lead, every booking, and every follow-up is tracked and reported in a unified dashboard that connects AI activity to business outcomes. You can see how many calls were answered, what percentage of chats converted to booked appointments, which lead sources produce the highest quality leads, and which qualification questions are most predictive of conversion.",
      "This is not just operational data — it is a feedback loop for continuous improvement. When you can see that a specific type of objection is handled poorly in 40% of conversations, you fix the response. When you can see that leads from one channel convert three times better than leads from another, you adjust your budget. The analytics make every other part of the system better over time.",
    ],
    problem: "Without good reporting, teams cannot tell which conversations are driving revenue and which parts of the system need work. Optimizing a system you cannot measure means making decisions based on instinct rather than evidence.",
    solution: "Omniweb tracks every conversation and connects it to downstream outcomes — bookings, CRM records, follow-up conversions, and revenue. The reporting layer gives you the visibility to continuously improve every part of the system.",
    valueToIndustry: "Measurement is the foundation of optimization. When businesses can see which AI activities produce revenue, they can invest more confidently and improve more systematically — which raises the overall standard of AI deployment.",
    valueToUser: "Your team makes better decisions about scripts, channels, and workflows because you have real data showing what works. You stop guessing and start optimizing.",
    outcome: "Continuous improvement in conversion rates, qualification quality, and response speed. Better resource allocation because you know which channels and workflows produce the best results. A clear picture of ROI from your AI investment.",
    features: [
      "Real-time conversation volume and outcome dashboard",
      "Lead quality scoring distribution by source and time period",
      "Booking and appointment conversion tracking",
      "Response time analytics for voice and chat",
      "Follow-up sequence performance — open rate, reply rate, conversion rate",
      "Qualification funnel analysis to spot drop-off points",
      "AI health score across all active assistants",
      "Exportable reports for stakeholder reviews",
    ],
    useCases: [
      "Revenue teams reviewing weekly performance and adjusting qualification logic",
      "Marketing teams attributing leads by source and channel",
      "Operations managers monitoring AI response quality and uptime",
      "Executives reviewing ROI and conversion benchmarks",
      "Sales managers coaching based on qualification data and call outcomes",
    ],
    howItWorks: [
      "Every interaction — voice call, chat session, form submission — is logged with its outcome. Booking, lead capture, transfer, and no-conversion outcomes are all tracked separately.",
      "The dashboard aggregates this data in real time and presents it by time period, lead source, conversation type, and qualification score. You can filter by any dimension to find the insights you need.",
      "Custom reports can be scheduled and exported for weekly reviews, stakeholder presentations, or external analysis. Alerts can be configured to notify you when performance drops below a defined threshold.",
    ],
    faq: [
      { question: "How far back does the reporting history go?", answer: "Omniweb retains reporting data for the full duration of your account. You can access historical performance for any time period since you went live." },
      { question: "Can I export data to my own BI tools?", answer: "Yes. Omniweb supports data export to CSV and integrates with common analytics platforms via API. You can also configure webhooks to push event data to your own data warehouse." },
      { question: "Does the AI improve itself based on the data?", answer: "Omniweb uses performance data to surface optimization recommendations. Some improvements are applied automatically, and others are surfaced as suggestions for you to review and approve." },
    ],
    related: ["/features/lead-automation", "/resources/compare", "/solutions/ai-agency"],
  },
  {
    slug: "website-knowledge-base",
    title: "Website Knowledge Base",
    summary: "Let Omniweb answer from your site content so every response sounds like it was written by your business.",
    overview: [
      "The most common complaint about chatbots is that they do not actually know anything about the business. They give generic answers, apologize for not understanding, and direct the visitor to call during business hours — which is exactly the behavior that makes visitors lose confidence and leave. The root cause is always the same: the AI was not trained on the business.",
      "Omniweb's Website Knowledge Base solves this at the foundation. Before your AI assistant has a single conversation, it ingests your website — service pages, product descriptions, FAQs, pricing, policies, and any additional documents you provide. The result is an AI that answers as if it has worked at your company for years.",
      "When a visitor asks whether you serve their neighborhood, the AI checks your service area page and answers accurately. When they ask about pricing, the AI pulls from your pricing page and gives the right range. When they ask about your warranty, the AI finds the relevant policy and explains it clearly. The knowledge base turns your existing content into a live, conversational resource.",
    ],
    problem: "Generic AI responses that do not reflect the actual business destroy trust and conversions. Visitors who ask a specific question and get a vague, incorrect, or redirected answer are less likely to convert than visitors who never opened the chat at all.",
    solution: "Omniweb ingests your website content and uses it as the foundation for every response the AI gives. The assistant draws from your actual pages, documents, and data — not from generic training data — so every answer is accurate, brand-consistent, and specific to your business.",
    valueToIndustry: "A knowledge base-powered AI raises the standard for what helpful means. The industry moves away from chatbots that frustrate visitors and toward AI that genuinely earns trust by being accurate and useful.",
    valueToUser: "Your existing website content becomes more valuable because it is actively used in every conversation. The effort you already put into your service pages, FAQs, and policy documents pays off every time a visitor asks a question.",
    outcome: "Visitors get accurate, specific answers instead of generic deflections. Trust builds faster. Conversion rates improve because the AI actually helps people find what they need. The knowledge base compound over time as you add more content.",
    features: [
      "Full website crawl and content ingestion",
      "Document upload support for PDFs, policies, and product sheets",
      "Real-time knowledge updates when your site changes",
      "Brand voice and tone matching",
      "Source-traceable answers so responses can be verified",
      "Multi-page knowledge architecture for complex businesses",
      "Knowledge gap alerts when questions cannot be answered from existing content",
      "Custom knowledge additions beyond the website",
    ],
    useCases: [
      "Service businesses with complex service area, pricing, and scope questions",
      "E-commerce stores where product and policy questions drive conversation volume",
      "Professional services firms with detailed FAQ and process documentation",
      "Healthcare and legal providers with sensitive, context-specific information",
      "Agencies deploying AI across multiple clients with different knowledge bases",
    ],
    howItWorks: [
      "During setup, Omniweb crawls your website and ingests the content into a structured knowledge graph. You can supplement this with uploaded documents for information not on the site.",
      "Every visitor question is matched against the knowledge graph to find the most relevant, accurate answer. The AI cites the source internally so responses are grounded in your actual content.",
      "When your website updates, Omniweb re-ingests the relevant pages so the knowledge base stays current. You can also trigger manual updates for time-sensitive information changes.",
    ],
    faq: [
      { question: "How long does the initial knowledge base setup take?", answer: "For most websites, the initial crawl and ingestion completes within a few hours. Larger sites or those with complex content may take up to a day. You will be notified when the knowledge base is ready for review." },
      { question: "What if my business has information that should not be shared publicly?", answer: "You control which content is included in the knowledge base. Sensitive information can be excluded from the crawl, and you can configure the AI to redirect certain questions to direct staff contact." },
      { question: "How does the AI handle questions it cannot answer from the knowledge base?", answer: "When the knowledge base does not have a clear answer, the AI acknowledges the limitation honestly and offers an alternative — contacting the team, being transferred, or providing a general framework for finding the answer." },
    ],
    related: ["/features/ai-chat-assistants", "/resources/docs", "/resources/guides"],
  },
  {
    slug: "video-presenter",
    title: "Video Presenter",
    summary: "Use a guided video presentation to explain offers, educate visitors, and keep people engaged longer.",
    overview: [
      "Some products and services require explanation before the visitor is ready to convert. A complex SaaS platform, a high-ticket service, or an unfamiliar technology all benefit from a visual walkthrough that builds understanding before it asks for a commitment. Text can describe, but video demonstrates — and demonstration is often the difference between hesitation and conversion.",
      "Omniweb's Video Presenter combines the engagement of video with the interactivity of AI. Instead of a static embed that plays once and leaves the visitor with questions, the Video Presenter creates a guided experience where the video explains the offer and the AI is available to answer the questions that come up in real time.",
      "The result is an experience that keeps visitors on the page longer, builds understanding faster, and converts at a higher rate than either video or chat alone. For high-consideration offers, it is the closest thing to having a real person walk the visitor through the product.",
    ],
    problem: "High-consideration buyers need more than a landing page headline to feel confident. Static video embeds lose attention, and visitors who leave to look up additional information rarely return. The gap between 'I want to learn more' and 'I am ready to act' is where most conversions are lost.",
    solution: "Omniweb pairs a polished video presentation with an AI that can answer questions, handle objections, and move the viewer toward a conversion action — all without leaving the page. The video and AI work together to close the education-to-action gap.",
    valueToIndustry: "Combining video and AI creates a new category of sales experience that is more effective than either alone. The industry benefits from a higher-quality way to present complex or high-value offers without live sales calls.",
    valueToUser: "You get a self-serve sales experience that works around the clock. Visitors who would previously have needed a discovery call to understand the offer can now get everything they need from the page — and then book when they are ready.",
    outcome: "Higher time-on-page, lower bounce rates on high-consideration pages, and a shorter path from visitor to booked or purchased. Sales teams spend less time on basic education calls and more time on motivated buyers.",
    features: [
      "Embedded video presentation with AI companion",
      "Real-time question answering during or after video playback",
      "Objection handling triggered by viewing patterns",
      "Chapter-based navigation for longer presentations",
      "Lead capture integrated into the video experience",
      "Mobile-optimized video and chat layout",
      "Analytics on video completion, question triggers, and conversion points",
      "Custom CTA placement at key moments in the video",
    ],
    useCases: [
      "SaaS product demos where the feature set needs explanation before a trial",
      "High-ticket service offers where trust must be built before booking",
      "Founder and brand story pages where narrative drives conversion",
      "Educational product launches where the buyer needs to understand before buying",
      "Agency or consulting presentations where the methodology needs demonstration",
    ],
    howItWorks: [
      "A video is embedded in the page alongside the AI assistant. The assistant is configured to know the content of the video so it can answer questions about what was covered at any point.",
      "As the visitor watches, engagement signals — pause points, replays, exit moments — can trigger the AI to proactively address likely questions or objections based on where the viewer is in the presentation.",
      "At key conversion moments, the AI presents a clear next step — booking a call, starting a trial, or requesting a quote — while the viewer is at peak engagement.",
    ],
    faq: [
      { question: "Does the AI know what is in the video?", answer: "Yes. During setup, you provide a transcript or outline of the video. The AI uses this to answer questions about the content and to know which topics are covered at which points in the presentation." },
      { question: "Can I use my existing video content?", answer: "Yes. Omniweb works with any video hosted on standard platforms or self-hosted. You do not need to reshoot or reformat your existing content." },
      { question: "How does the lead capture work within the video experience?", answer: "You can configure lead capture forms to appear at specific timestamps or when the viewer reaches the end of the video. The AI can also ask for contact details conversationally when the viewer expresses interest." },
    ],
    related: ["/features/ai-chat-assistants", "/resources/blog", "/solutions/ecommerce"],
  },
  {
    slug: "workflow-automation",
    title: "Workflow Automation",
    summary: "Connect the front-end conversation to the systems that execute the follow-up and routing work.",
    overview: [
      "A conversation that ends without triggering the right next action is a conversation that generated no revenue. Capturing a lead is only the first step. What happens in the 60 minutes after the conversation ends — whether a CRM record is created, a follow-up is sent, a rep is notified, a task is assigned, and a reminder is scheduled — is what actually determines whether that conversation converts.",
      "Omniweb's Workflow Automation layer handles all of that. Every conversation outcome triggers a predefined sequence of actions across your systems: the lead is logged, the follow-up is sent, the rep is notified, the task is created, and the calendar is updated — all automatically, in the order you configured, without anyone needing to manually connect the dots.",
      "For teams that have struggled with follow-up consistency or CRM hygiene, this is the layer that makes everything else reliable. For businesses growing faster than their manual processes can keep up with, it is what allows them to scale without proportionally increasing admin headcount.",
    ],
    problem: "Manual handoffs between the conversation and the systems that execute follow-up create delay, inconsistency, and lost opportunities. Every step that requires human action is a step that can be skipped, delayed, or done differently by different people.",
    solution: "Omniweb connects every conversation outcome to a sequence of automated actions across your tech stack. The trigger is the conversation. The actions are configured by you. The execution is automatic.",
    valueToIndustry: "Workflow automation turns AI conversations from data collection events into operational drivers. The whole revenue system — not just the front end — becomes more consistent and scalable.",
    valueToUser: "Your team executes the same high-quality follow-up process on every lead, at every time of day, without manual effort. The system does not take days off, forget steps, or make different decisions for different leads.",
    outcome: "Every lead is followed up on correctly and on time. Every team member has the context they need when they pick up a conversation. Every system stays in sync. Revenue that would have slipped through process gaps gets captured instead.",
    features: [
      "Trigger-based automation from conversation outcomes",
      "Multi-step workflow sequences across email, SMS, CRM, and tasks",
      "Conditional logic based on lead score, intent, or qualification result",
      "Cross-platform action execution via integrations and webhooks",
      "Automated notifications to reps and managers",
      "Time-delayed actions for scheduled follow-up sequences",
      "Error handling and retry logic for failed actions",
      "Workflow performance monitoring and logging",
    ],
    useCases: [
      "Sales teams automating the path from conversation to booked demo",
      "Service businesses triggering dispatch workflows from AI qualification",
      "Agencies managing multi-step client follow-up across multiple platforms",
      "E-commerce brands automating cart recovery and post-purchase sequences",
      "Professional services firms managing intake-to-consultation workflows",
    ],
    howItWorks: [
      "When a conversation ends with a defined outcome — qualified lead, booked appointment, objection raised, low intent — the automation engine reads the outcome and determines which workflow to trigger.",
      "The workflow executes each configured step in sequence: create the CRM record, send the follow-up email, notify the assigned rep, create the task with the deadline, and schedule the reminder. Each step includes error handling.",
      "The workflow runs in the background while your team focuses on the conversations worth having. You can monitor workflow execution in the dashboard and configure alerts for failures or unusual patterns.",
    ],
    faq: [
      { question: "Can I build complex multi-branch workflows?", answer: "Yes. Omniweb's workflow builder supports conditional branching based on any conversation data — lead score, service type, location, stated timeline — so different types of leads follow different paths." },
      { question: "What systems can workflows connect to?", answer: "We support native connections to CRM platforms, email and SMS providers, calendar tools, task managers, and Slack. For anything else, we provide webhook and API triggers that can connect to any system." },
      { question: "How do I know if a workflow step failed?", answer: "Failed steps are logged in the workflow monitor and you receive a notification based on your configured alert preferences. Failed steps can be retried automatically or escalated for manual review." },
    ],
    related: ["/features/lead-automation", "/features/crm-integrations", "/solutions/ai-agency"],
  },
]

export const featurePages: Record<string, PageEntry> = Object.fromEntries(
  featureSeeds.map((seed) => [
    seed.slug,
    buildPageEntry({
      sectionLabel: "FEATURES",
      primaryAction: primary,
      secondaryAction: secondary,
      footerEyebrow: "Ready to turn a feature into a live system?",
      footerTitle: "Install the capability on your website and start qualifying more revenue.",
      footerDescription: "Each feature page connects you to the same Omniweb engine — voice, chat, automation, and measurable outcomes that compound over time.",
      seed,
      stats: [
        { value: "24/7", label: "Coverage" },
        { value: "< 2s", label: "Response" },
        { value: "1", label: "Platform" },
        { value: "100%", label: "Connected system" },
      ],
    }),
  ])
) as Record<string, PageEntry>
