import { buildPageEntry, type PageEntry } from "@/lib/marketing-page-data"

const primary = { label: "View Pricing", href: "/pricing" }
const secondary = { label: "Book a Demo", href: "/company/book-demo" }

const pricingSeeds = [
  {
    slug: "voice-agent",
    title: "Voice Agent Pricing",
    summary: "Transparent pricing for AI voice agents — per minute, per call, or flat monthly depending on your volume.",
    overview: [
      "AI voice agents are sold by the minute, by the call, or by the month depending on the vendor and the plan. Omniweb's voice agent pricing is designed to be straightforward: you know what you are paying for, you can predict your costs from your call volume, and there are no hidden fees for features that should be standard — like custom greetings, call routing configuration, or voicemail handling.",
      "The voice agent plan covers inbound call answering, qualification, routing, and automated follow-up. It includes the setup of up to five custom call flows, the knowledge base that the AI uses to answer questions and qualify callers, and the reporting dashboard where you monitor call volume, qualification rates, and conversion outcomes.",
      "For businesses with predictable call volume, the flat monthly plan provides cost certainty. For businesses with variable or seasonal volume, the per-minute plan lets you pay for what you use without over-committing. Both options include the full feature set — the only difference is the billing model.",
      "We do not charge setup fees, and the first 30 days are included in the free trial. If you decide Omniweb is not right for you within the first 30 days, you pay nothing.",
    ],
    problem: "Voice AI pricing is often complex, opaque, or buried under overage fees that make actual monthly costs hard to predict. Businesses need clear, honest pricing that reflects the value they receive without surprises on the invoice.",
    solution: "Omniweb's voice agent pricing offers two models — flat monthly and per-minute — with full feature access on both. No setup fees. No hidden charges for standard features. Predictable costs from the first month.",
    valueToIndustry: "Transparent pricing builds trust and accelerates adoption. When businesses can accurately evaluate the ROI of AI voice agents before committing, more businesses invest — and the industry grows.",
    valueToUser: "You know exactly what you are paying before you start. You can model the ROI of the voice agent against your current call volume and conversion rates. You do not discover unexpected fees after the fact.",
    outcome: "Clear monthly costs, no billing surprises, and an ROI calculation that is straightforward to make before you sign up.",
    features: [
      "Inbound call answering, qualification, and routing",
      "Up to 5 custom call flow configurations",
      "Knowledge base for AI-powered caller Q&A",
      "Automated SMS follow-up after calls",
      "Call recording and transcript access",
      "Reporting dashboard with call volume and outcome metrics",
      "After-hours and 24/7 answering coverage",
      "30-day free trial with no setup fee",
    ],
    useCases: [
      "Service businesses replacing or supplementing a receptionist with AI voice coverage",
      "Businesses with predictable monthly call volume using the flat monthly plan",
      "Seasonal businesses using per-minute billing to avoid paying for idle capacity",
      "Teams evaluating voice AI ROI before committing to a full deployment",
      "Agencies pricing voice agent plans for client proposals",
    ],
    howItWorks: [
      "Select the flat monthly or per-minute billing model based on your call volume predictability. Both include the full voice agent feature set.",
      "Complete the onboarding flow to configure your call flows, upload your knowledge base content, and connect your phone number. Most setups take under two hours.",
      "Monitor your usage and costs from the billing dashboard. Upgrade, downgrade, or switch billing models at any time from your account settings.",
    ],
    faq: [
      { question: "Is there a setup fee?", answer: "No. There is no setup fee for any Omniweb voice agent plan. The 30-day free trial includes full access to the platform and counts toward your first billing period only after the trial ends." },
      { question: "What happens when I exceed my plan's minute limit?", answer: "On flat monthly plans, overage minutes are billed at the per-minute rate listed in your plan details. You can set usage alerts to notify you before you hit the overage threshold." },
    ],
    related: ["/features/ai-voice-agents", "/pricing/combo", "/pricing/enterprise"],
  },
  {
    slug: "chat-assistant",
    title: "Chat Assistant Pricing",
    summary: "Pricing for website and messaging AI chat assistants — by conversation volume or flat monthly.",
    overview: [
      "Chat assistant pricing at Omniweb is built around conversations, not seats. You pay based on how many real customer conversations the AI handles per month — not for a license that sits unused, not for contacts that never interact with the AI, and not for features that you need but were not included in the base tier.",
      "The chat assistant plan covers website chat, lead capture, FAQ handling, appointment booking, and follow-up automation. It includes the AI knowledge base configuration, the embed code for your website, and the dashboard where you manage conversations, review lead data, and monitor performance.",
      "For businesses launching AI chat for the first time, the starter conversation volume covers most small business website traffic. As your traffic grows, upgrading is a single click from the billing settings. There are no contracts that lock you into a conversation volume above what you need.",
    ],
    problem: "Chat assistant pricing models are often misaligned with how value is actually delivered — charging per seat instead of per conversation, or per contact instead of per active interaction. This makes it hard for businesses to evaluate ROI.",
    solution: "Omniweb's chat assistant pricing is conversation-based, aligning the cost directly with the volume of value the AI delivers. Pay for conversations handled, not for licenses or contacts.",
    valueToIndustry: "Conversation-based pricing models create clearer ROI calculations and better alignment between the vendor and the customer. When pricing reflects actual value delivery, both sides benefit.",
    valueToUser: "You pay for what the AI actually does — customer conversations handled, leads captured, and appointments booked. As your volume grows, your costs grow proportionally. There are no surprises.",
    outcome: "Predictable, volume-aligned costs. Clear ROI calculation based on conversations handled vs. leads converted. No overcharging during low-traffic periods.",
    features: [
      "Website chat deployment via embed code",
      "Lead capture and contact information collection",
      "FAQ and product question handling from your knowledge base",
      "Appointment booking integration",
      "Automated follow-up after chat conversations",
      "Conversation history and lead data dashboard",
      "Multi-language conversation support",
      "30-day free trial",
    ],
    useCases: [
      "E-commerce stores adding AI chat to handle product questions and recover abandoned sessions",
      "Service businesses using chat to qualify web visitors and book consultations",
      "B2B companies adding chat to their lead capture flow",
      "Professional services firms fielding FAQ and intake questions from website traffic",
      "Agencies deploying chat assistants for multiple clients on a per-conversation billing model",
    ],
    howItWorks: [
      "Select your monthly conversation volume tier. If you are unsure, start with the tier that matches your current website traffic and upgrade as needed.",
      "Install the embed code on your website, configure your knowledge base, and set your lead capture fields. The assistant is ready for visitors within minutes.",
      "Monitor conversation volume from your dashboard and upgrade your tier with one click when you approach the limit.",
    ],
    faq: [
      { question: "What counts as a conversation?", answer: "A conversation is any session where a website visitor exchanges at least one message with the AI assistant. Visitors who see the widget but do not engage are not counted." },
      { question: "Can I white-label the chat widget?", answer: "Yes. The chat widget is fully customizable — you can match your brand colors, name the assistant, and set the greeting message. White-label options for agency deployments are available on the agency plan." },
    ],
    related: ["/features/ai-chat-assistants", "/pricing/combo", "/pricing/shopify"],
  },
  {
    slug: "ai-telephony",
    title: "AI Telephony Pricing",
    summary: "Pricing for AI-powered phone infrastructure — inbound, outbound, and full-call handling at scale.",
    overview: [
      "AI telephony is distinct from a voice agent add-on. It is the infrastructure layer that handles routing, recording, transcription, and automation across all your phone traffic — not just the initial greeting. Omniweb's AI telephony pricing covers the full call stack: phone number provisioning, inbound routing, outbound dialing, call recording, real-time transcription, and the automation layer that triggers follow-up actions based on call outcomes.",
      "For businesses with high call volumes — call centers, dispatch operations, multi-location service companies, or any operation where phone is the primary customer communication channel — telephony pricing is built around volume tiers with predictable per-minute rates at each level. There are no hidden infrastructure fees, and phone number provisioning is included.",
      "Outbound dialing is included in the telephony plan for automated follow-up, appointment reminders, and re-engagement campaigns. Outbound minutes are metered separately from inbound and at a different rate, which is documented in the plan details before you sign up.",
    ],
    problem: "Business telephony is notoriously complex and expensive. Hidden infrastructure fees, per-number provisioning charges, and overage rates on recordings and transcription create bills that are difficult to predict and hard to audit.",
    solution: "Omniweb's AI telephony pricing bundles the full call stack — routing, recording, transcription, and automation — into a single volume-tiered plan with no hidden infrastructure fees and transparent per-minute rates.",
    valueToIndustry: "Predictable telephony costs lower the barrier to AI phone infrastructure adoption. When businesses can accurately model telephony costs at scale, more of them invest in the capabilities that create competitive advantage.",
    valueToUser: "You know your telephony costs at every volume level before you sign up. The full feature set is included at every tier. There are no surprises when the invoice arrives.",
    outcome: "Predictable monthly telephony costs, full infrastructure coverage with no hidden fees, and the automated call handling that reduces the manual labor in your phone operations.",
    features: [
      "Phone number provisioning included in all plans",
      "Inbound call routing and handling",
      "Outbound dialing for follow-up and reminder automation",
      "Call recording with configurable retention",
      "Real-time transcription and call summary",
      "IVR and routing flow configuration",
      "Integration with your CRM for call logging",
      "Volume-based pricing with no per-feature add-ons",
    ],
    useCases: [
      "Multi-location service businesses handling high inbound call volume",
      "Dispatch operations automating inbound intake and routing",
      "Sales teams using outbound dialing for follow-up automation",
      "Call center operations augmenting human agents with AI handling",
      "Businesses replacing manual phone intake with AI-managed qualification",
    ],
    howItWorks: [
      "Select the volume tier that matches your average monthly call minutes. Inbound and outbound rates are listed separately at each tier.",
      "Provision your phone numbers through the Omniweb dashboard or bring your existing numbers via number porting. Configuration is completed through the routing flow builder.",
      "Monitor your usage and costs from the billing dashboard. Volume tier upgrades take effect immediately and are prorated for the remainder of the billing period.",
    ],
    faq: [
      { question: "Can I port my existing business phone number?", answer: "Yes. Number porting is supported for US and Canadian numbers. The porting process typically takes 3-7 business days. Your existing number will continue to receive calls during the porting process." },
      { question: "Is call recording storage included in the plan?", answer: "Call recordings are stored for 90 days by default at no additional cost. Extended retention periods are available as an add-on for compliance-sensitive use cases." },
    ],
    related: ["/features/ai-voice-agents", "/pricing/combo", "/solutions/roadside-assistance"],
  },
  {
    slug: "combo",
    title: "Voice + Chat Combo",
    summary: "The most popular plan — voice and chat AI together with a unified lead view and full automation.",
    overview: [
      "Most businesses that benefit from AI voice also benefit from AI chat — because their customers reach out through multiple channels. A homeowner looking for a contractor might call on Monday morning and fill out the website form on a Tuesday evening. A shopper might ask a question in the chat widget and then follow up over email. When voice and chat are separate systems, leads fall through the cracks between them.",
      "The Omniweb Voice + Chat Combo plan deploys both AI systems under a single account, with a unified lead record that captures every interaction regardless of channel. When a customer who chatted on the website calls two days later, the voice AI recognizes the context and handles the follow-up conversation with full background.",
      "The combo plan is the most popular Omniweb plan because it matches how customers actually behave — across channels, on their own schedule, in whatever format is most convenient at the moment. Businesses that deploy both voice and chat consistently outperform single-channel deployments on lead capture rate and conversion.",
    ],
    problem: "Single-channel AI deployments capture only a fraction of available leads. Customers who prefer to call are missed by chat-only systems. Customers who prefer to message are missed by voice-only systems. The gap between channels is a gap in your lead capture.",
    solution: "The Voice + Chat Combo deploys both AI systems under a unified account with shared lead records — ensuring that every channel is covered and every customer interaction is captured regardless of how the customer prefers to reach out.",
    valueToIndustry: "Multi-channel AI coverage raises the floor on lead capture rates across the industry. Businesses that capture leads from every channel convert more of their marketing spend into revenue.",
    valueToUser: "You stop losing leads because a customer called instead of chatting, or chatted instead of calling. Every channel is covered. Every lead is captured. The reporting shows you the full picture.",
    outcome: "Higher overall lead capture rate, unified customer view across channels, and better conversion because every follow-up has full context from all prior interactions.",
    features: [
      "AI voice agent for inbound call handling",
      "AI chat assistant for website and messaging",
      "Unified lead record across voice and chat",
      "Shared knowledge base for consistent AI responses",
      "Cross-channel follow-up automation",
      "Combined reporting dashboard",
      "Single account billing for both channels",
      "Priority support for combo plan customers",
    ],
    useCases: [
      "Service businesses where customers call, text, and fill out web forms",
      "E-commerce stores with both website chat and customer service phone lines",
      "Healthcare practices handling scheduling through phone and online channels",
      "Professional services firms responding to website inquiries and incoming calls",
      "Any business where multi-channel lead capture is a revenue priority",
    ],
    howItWorks: [
      "Sign up for the combo plan and complete the setup for both voice and chat through a single onboarding flow. Voice and chat are configured from the same dashboard.",
      "The shared knowledge base ensures that the AI delivers consistent answers regardless of whether the customer calls or chats. Configure it once, apply it to both channels.",
      "When a lead interacts through multiple channels, the unified lead record captures every touchpoint so your team can follow up with full context.",
    ],
    faq: [
      { question: "Is the combo plan discounted compared to buying voice and chat separately?", answer: "Yes. The combo plan is priced at a discount compared to purchasing both plans individually. The discount is shown on the pricing page when you view the combo vs. individual plan comparison." },
      { question: "Can I add the combo to a trial account?", answer: "Yes. The 30-day free trial applies to the combo plan and includes full access to both voice and chat features for the duration of the trial." },
    ],
    related: ["/pricing/voice-agent", "/pricing/chat-assistant", "/features/lead-automation"],
  },
  {
    slug: "enterprise",
    title: "Enterprise Pricing",
    summary: "Custom pricing for high-volume and complex deployments — with dedicated support and SLA guarantees.",
    overview: [
      "Enterprise deployments have requirements that standard plans are not designed for: custom SLAs, dedicated infrastructure, white-glove onboarding, compliance documentation, custom integrations, and pricing that reflects commitment volume rather than month-to-month pay-as-you-go rates.",
      "Omniweb's enterprise plan is built for organizations where AI is a core operational infrastructure, not a tool added to an existing workflow. These are deployments where the AI handles thousands of conversations per day, where downtime has measurable revenue impact, and where the compliance, security, and data handling requirements go beyond what a standard plan can address.",
      "The enterprise engagement starts with a discovery conversation to understand the specific requirements: volume, compliance, integration complexity, team structure, and timeline. From that conversation, we build a custom proposal that covers pricing, SLA terms, onboarding plan, and ongoing support structure.",
      "Enterprise customers are assigned a dedicated account manager and a dedicated technical contact. Onboarding is supported by the implementation team. Ongoing performance reviews are scheduled quarterly.",
    ],
    problem: "Standard SaaS plans are not designed for enterprise-scale deployments. Volume-based overages, self-service onboarding, and standard support tiers are not appropriate for organizations where AI is a core operational system with compliance and availability requirements.",
    solution: "Omniweb's enterprise plan provides custom pricing based on committed volume, dedicated support, compliance documentation, custom SLA terms, and a white-glove onboarding experience designed for complex organizational requirements.",
    valueToIndustry: "Enterprise-grade AI deployments raise the standard for what AI in business can accomplish. When large organizations deploy AI at scale with proper support and infrastructure, the benchmark for AI performance improves across the market.",
    valueToUser: "You get pricing that reflects your commitment volume, infrastructure that is designed for your scale, support that is available when you need it, and compliance documentation that satisfies your procurement and legal requirements.",
    outcome: "Deployed at scale with the SLA guarantees, compliance coverage, and dedicated support that your organization requires — not adapted from a self-service tool.",
    features: [
      "Custom volume-based pricing negotiated at commitment level",
      "Dedicated account manager and technical contact",
      "99.9% uptime SLA with monitoring and incident response",
      "White-glove onboarding and implementation support",
      "Custom integration development for internal systems",
      "SOC 2, HIPAA, and GDPR compliance documentation",
      "Priority support with 1-hour response SLA",
      "Quarterly business reviews and performance optimization",
    ],
    useCases: [
      "Large service organizations handling thousands of inbound interactions daily",
      "Healthcare systems deploying AI patient communication at scale",
      "Multi-location franchise operations standardizing AI across hundreds of locations",
      "Financial services organizations with compliance-specific deployment requirements",
      "Enterprise sales operations deploying AI across a large field team",
    ],
    howItWorks: [
      "Contact our enterprise sales team to begin the discovery process. The initial conversation covers your use case, volume, compliance requirements, and timeline.",
      "The enterprise team prepares a custom proposal covering pricing, SLA terms, onboarding plan, and support structure. Most proposals are delivered within five business days.",
      "After contract execution, the implementation team leads the onboarding process. Enterprise deployments typically go live within 30-60 days depending on integration complexity.",
    ],
    faq: [
      { question: "What is the minimum volume for the enterprise plan?", answer: "Enterprise pricing is available for organizations with more than 10,000 AI-handled interactions per month. Smaller organizations may find the combo or individual feature plans more cost-effective." },
      { question: "What does the SLA cover?", answer: "The enterprise SLA covers platform uptime, response time for support tickets, and resolution time for platform-affecting incidents. Specific SLA terms are negotiated as part of the enterprise contract." },
    ],
    related: ["/pricing/combo", "/company/about", "/resources/security"],
  },
  {
    slug: "shopify",
    title: "Shopify AI Pricing",
    summary: "Pricing for the Omniweb Shopify AI assistant — designed for store size, traffic volume, and revenue impact.",
    overview: [
      "Shopify stores have a fundamentally different value calculation than service businesses when it comes to AI. For a Shopify store, the AI assistant's primary job is to increase revenue from existing traffic — by converting more browsers to buyers, recovering abandoned carts, and reducing the abandonment that comes from unanswered questions. The ROI calculation is straightforward: if the AI recovers five percent more carts from your monthly traffic, what is that worth in revenue?",
      "Omniweb's Shopify AI pricing is built around store revenue volume rather than conversation count. Starter stores pay less; high-revenue stores pay more — because the revenue recovery opportunity scales with store size, and so should the pricing.",
      "The Shopify AI plan includes the full feature set: catalog ingestion, real-time product Q&A, cart abandonment recovery, order status handling, post-purchase follow-up, and the analytics dashboard that shows you exactly what revenue the AI recovered. There are no features held back for higher tiers; every store gets the same AI capabilities.",
    ],
    problem: "E-commerce AI pricing is often tied to conversation volume or contacts — metrics that do not directly reflect the value delivered. A store that converts ten percent more of its traffic creates far more value than one that has ten percent more conversations.",
    solution: "Omniweb's Shopify AI pricing is based on store revenue volume — aligning the cost with the scale of the revenue recovery opportunity and making the ROI calculation simple and honest.",
    valueToIndustry: "Revenue-based pricing models for e-commerce AI align vendor incentives with store outcomes. When the AI vendor's revenue grows with store revenue, both sides are motivated by the same outcome.",
    valueToUser: "You pay a price that scales with your store's revenue opportunity. The ROI calculation is transparent: compare the plan cost against the revenue the AI recovered dashboard shows.",
    outcome: "Predictable AI cost relative to store revenue. Clear recovery attribution in the analytics dashboard. Full feature access at every tier so you can deploy every capability from day one.",
    features: [
      "Full Shopify catalog and policy ingestion",
      "Real-time product question answering",
      "Cart abandonment recovery conversations",
      "Order status and tracking question handling",
      "Return and exchange policy explanation",
      "Post-purchase follow-up and review requests",
      "Revenue recovery attribution in the analytics dashboard",
      "Multi-currency and international shipping support",
    ],
    useCases: [
      "DTC Shopify stores with active paid traffic looking to improve conversion",
      "Shopify Plus brands with high-SKU catalogs and complex product questions",
      "Subscription product stores managing recurring customer questions",
      "Seasonal stores with traffic spikes that require scalable AI coverage",
      "New stores looking to maximize conversion from early traffic without a support team",
    ],
    howItWorks: [
      "Select the tier that corresponds to your store's monthly revenue range. All tiers include the full Shopify AI feature set.",
      "Connect your Shopify store through the OAuth authentication flow. Omniweb ingests your catalog, policies, and FAQ content automatically.",
      "Monitor the revenue recovery attribution dashboard to see exactly what the AI is contributing to your store's revenue on a monthly basis.",
    ],
    faq: [
      { question: "What if my store revenue grows and I need to move to the next tier?", answer: "Tier upgrades are applied at the start of the next billing period when your monthly revenue crosses the tier threshold. You receive a notification before the change takes effect." },
      { question: "How does the AI know which carts have been abandoned?", answer: "Omniweb's Shopify integration monitors session activity and cart events. When a cart is left without checkout for a configurable period, the recovery sequence is triggered automatically." },
    ],
    related: ["/solutions/shopify-ai-assistant", "/features/ai-chat-assistants", "/pricing/combo"],
  },
  {
    slug: "agency",
    title: "Agency Pricing",
    summary: "Multi-client pricing for AI agencies — manage deployments, billing, and reporting across all accounts.",
    overview: [
      "AI agencies need a pricing model that reflects how they actually operate: multiple client accounts, each with their own configuration, volume, and billing relationship. Standard per-seat or per-conversation plans that work for single businesses do not translate cleanly to multi-client agency operations.",
      "Omniweb's agency plan is built for the agency business model. You manage a portfolio of client accounts from a single dashboard, each with its own configuration and reporting. Client billing can be managed through Omniweb's client invoicing feature, or you can handle billing directly with your clients and pay Omniweb the wholesale rate for each account.",
      "The agency plan includes white-labeling so your clients see your brand, not Omniweb's. It includes the multi-tenant management tools that let you configure and update client accounts at scale. And it includes the reporting infrastructure that lets you demonstrate performance to clients in a professional, branded format.",
      "Pricing is tiered by the number of active client accounts you manage. The per-account rate decreases as your portfolio grows, reflecting the economies of scale in a larger agency operation.",
    ],
    problem: "Standard SaaS plans force agencies to manage separate accounts for each client, pay full retail price per client, and manually aggregate reporting across accounts. This model caps margin and creates operational overhead that grows linearly with client count.",
    solution: "Omniweb's agency plan provides multi-tenant management, wholesale per-account pricing, white-labeling, and centralized reporting — designed for the economics and operational realities of an AI agency.",
    valueToIndustry: "Well-priced agency plans make AI services accessible to a broader market by enabling agencies to profitably serve mid-market clients. When agencies can deploy AI economically, more businesses benefit.",
    valueToUser: "You manage all client accounts from one dashboard at wholesale rates that improve as your portfolio grows. Your clients see your brand. Your reporting tells the performance story professionally.",
    outcome: "Better margin per client account. More clients managed per team member. Professional client reporting that strengthens retention. A deployment model that scales.",
    features: [
      "Multi-tenant client account management",
      "Wholesale per-account pricing with volume discounts",
      "White-label AI assistant branding for all client accounts",
      "Centralized configuration and deployment tools",
      "Client-specific reporting dashboards",
      "Cross-account performance analytics",
      "Client billing management through Omniweb invoicing",
      "Priority support for agency accounts",
    ],
    useCases: [
      "AI agencies managing 5 to 500 client deployments",
      "Digital marketing agencies adding AI as a managed service offering",
      "Business process consultants delivering AI intake systems to SMB clients",
      "Franchise systems standardizing AI communication across all locations",
      "SaaS companies building Omniweb into their product offering under their own brand",
    ],
    howItWorks: [
      "Sign up for the agency plan and configure your agency account with your branding. Create client accounts from the agency dashboard with individual configurations for each.",
      "Deploy client AI systems using the template library and adapt each deployment to the client's specific knowledge base and qualification requirements.",
      "Monitor all client account performance from the central dashboard and generate client-specific performance reports using the branded reporting tool.",
    ],
    faq: [
      { question: "Can I add client accounts without contacting support?", answer: "Yes. Client accounts are created self-service from the agency dashboard. You can add, configure, and activate new client accounts without any manual process on our end." },
      { question: "How does client billing work?", answer: "You have two options: use Omniweb's client invoicing feature to bill your clients directly through the platform, or handle your own client billing and pay Omniweb the wholesale rate for each account on your monthly invoice." },
    ],
    related: ["/solutions/ai-agency", "/resources/guides", "/pricing/enterprise"],
  },
  {
    slug: "faq",
    title: "Pricing FAQ",
    summary: "Answers to the most common questions about Omniweb pricing, billing, contracts, and trials.",
    overview: [
      "Pricing questions are almost always the same: What does it actually cost? Are there hidden fees? What happens if I exceed my plan limits? Can I cancel? Is there a free trial? We have compiled honest answers to all of these questions in one place because the worst version of a sales process is one where the customer discovers fees and constraints after they have committed.",
      "The Omniweb pricing philosophy is straightforward: you should be able to predict your costs before you sign up, understand exactly what happens at every volume threshold, and trust that the price you see is the price you pay without surprises. Our plans are designed to make the ROI calculation easy, not to obscure it.",
      "If you have a question that is not covered here, the chat assistant in the bottom corner of this page will answer it directly — or escalate to a human if the question requires a specific account discussion.",
    ],
    problem: "Software pricing pages often obscure true costs through confusing tier structures, undisclosed add-ons, and terms that are only visible after account creation. Prospects cannot make good decisions without complete, honest pricing information.",
    solution: "Omniweb publishes complete pricing information with honest answers to the questions that typically require a sales call to answer — so you can evaluate fit independently before talking to anyone on our team.",
    valueToIndustry: "Transparent pricing builds market trust and improves evaluation quality. When buyers can assess value before committing, the decisions are better for both sides.",
    valueToUser: "You have all the information you need to make a confident buying decision without going through a sales process to get to the actual numbers.",
    outcome: "Confident, well-informed purchasing decisions. No surprises after signup. ROI calculations you can make before you commit.",
    features: [
      "Complete tier comparison across all plans",
      "Honest overage and usage limit explanation",
      "Free trial terms and duration detail",
      "Cancellation and refund policy",
      "Contract vs. month-to-month options",
      "Payment method options",
      "Upgrade and downgrade process explanation",
      "Enterprise custom pricing process",
    ],
    useCases: [
      "Business owners evaluating Omniweb before starting a trial",
      "Finance teams reviewing SaaS spend and billing model",
      "Procurement teams reviewing contract and commitment terms",
      "Agencies modeling client pricing based on Omniweb's wholesale rates",
      "Teams comparing Omniweb pricing against competitor platforms",
    ],
    howItWorks: [
      "Browse the FAQ by category — billing, trials, contracts, usage, and enterprise. Each question has a complete, honest answer without qualification or deflection.",
      "If you have a question that is not answered here, use the chat assistant at the bottom of the page or contact our sales team directly.",
      "For enterprise or custom pricing questions, use the Book a Demo link to schedule a conversation with our team.",
    ],
    faq: [
      { question: "Is there a free trial?", answer: "Yes. Every plan includes a 30-day free trial with full feature access. No credit card is required to start the trial. If you decide to subscribe after the trial, you enter your payment information at that point." },
      { question: "Can I cancel at any time?", answer: "Yes. Month-to-month plans can be cancelled at any time with no cancellation fee. Your account remains active through the end of the current billing period after cancellation." },
      { question: "Are there annual contract discounts?", answer: "Yes. Annual prepayment is available at a discount of approximately 15-20% depending on the plan. Annual plans are billed upfront and are non-refundable after the first 30 days." },
      { question: "What payment methods are accepted?", answer: "We accept all major credit cards and ACH bank transfer for US accounts. Enterprise customers can also pay via purchase order with net 30 terms." },
    ],
    related: ["/pricing/voice-agent", "/pricing/combo", "/pricing/enterprise"],
  },
]

export const pricingPages: Record<string, PageEntry> = Object.fromEntries(
  pricingSeeds.map((seed) => [
    seed.slug,
    buildPageEntry({
      sectionLabel: "PRICING",
      primaryAction: primary,
      secondaryAction: secondary,
      footerEyebrow: "Ready to talk numbers?",
      footerTitle: "See exactly what Omniweb costs for your volume and use case.",
      footerDescription: "Transparent pricing, no hidden fees, and a 30-day free trial. Start with any plan and upgrade when you are ready.",
      seed,
      stats: [
        { value: "30", label: "Day free trial" },
        { value: "0", label: "Setup fees" },
        { value: "4", label: "Plan types" },
        { value: "100%", label: "Feature access" },
      ],
    }),
  ])
) as Record<string, PageEntry>
