import { buildPageEntry, type PageEntry } from "@/lib/marketing-page-data"

const primary = { label: "See Pricing", href: "/pricing" }
const secondary = { label: "Book a Demo", href: "/company/book-demo" }

const pricingSeeds = [
  {
    slug: "voice-agent",
    title: "Voice Agent Pricing",
    summary: "Price always-on phone coverage for teams that rely on calls to close business.",
    problem: "Voice volume is hard to staff for and too costly to leave unanswered.",
    solution: "Omniweb packages voice coverage around the outcomes that matter: answered calls, qualified leads, and booked next steps.",
    valueToIndustry: "The pricing model helps the market buy call coverage as a growth lever rather than a support cost.",
    valueToUser: "Your team can scale voice coverage without hiring more front-desk staff.",
    outcome: "More calls get answered and more of them turn into revenue.",
    features: ["After-hours coverage", "Qualification flow", "Booking support", "Call summaries"],
    useCases: ["Inbound sales calls", "Urgent service requests", "High-value lead intake"],
    howItWorks: ["Pick the voice coverage level", "Add the qualification flow", "Track bookings and outcomes"],
    related: ["/features/ai-voice-agents", "/pricing/ai-telephony", "/company/book-demo"],
  },
  {
    slug: "chat-assistant",
    title: "Chat Assistant Pricing",
    summary: "Choose a chat plan that keeps website visitors engaged and moving toward conversion.",
    problem: "Chat can be effective, but only if it responds fast and understands the business context.",
    solution: "Omniweb pricing is built so the chat assistant can be deployed as a live conversion channel.",
    valueToIndustry: "The industry gets a clearer way to buy conversational coverage for the website.",
    valueToUser: "Your team can launch chat without overpaying for tools that do not close the loop.",
    outcome: "More visitors turn into conversations and fewer leave unanswered.",
    features: ["Website chat", "Objection handling", "Lead capture", "Conversation summaries"],
    useCases: ["Lead generation pages", "Product support", "High-intent visitors"],
    howItWorks: ["Choose the chat plan", "Connect your website context", "Measure qualified conversations"],
    related: ["/features/ai-chat-assistants", "/pricing/combo", "/company/book-demo"],
  },
  {
    slug: "ai-telephony",
    title: "AI Telephony Pricing",
    summary: "Package the telephony layer that keeps every call routed, tracked, and useful to the sales team.",
    problem: "Phone systems can be powerful, but the workflow breaks down when calls are not qualified or summarized.",
    solution: "Omniweb pricing includes the telephony support needed to turn every call into structured revenue data.",
    valueToIndustry: "The market gets a modern call-handling layer instead of a static phone tree.",
    valueToUser: "Your team can run a responsive phone workflow without building it from scratch.",
    outcome: "Cleaner call handling and better visibility into every interaction.",
    features: ["Call handling", "Routing logic", "Conversation summaries", "Lead handoff"],
    useCases: ["Inbound call centers", "Service businesses", "Fast-response sales teams"],
    howItWorks: ["Set the telephony workflow", "Capture the call outcome", "Push the result downstream"],
    related: ["/features/ai-voice-agents", "/solutions/local-service-businesses", "/pricing/combo"],
  },
  {
    slug: "combo",
    title: "Combo Plan Pricing",
    summary: "Bundle voice, chat, automation, and routing into one system that covers the full customer journey.",
    problem: "Point tools create gaps between channels and make the experience harder to manage.",
    solution: "Combo pricing keeps the front-end conversation, the follow-up workflow, and the conversion step in one platform.",
    valueToIndustry: "The industry gets a simpler, more complete buying model for AI revenue systems.",
    valueToUser: "Your team manages one platform instead of stitching multiple tools together.",
    outcome: "Less complexity, more control, and a cleaner path from traffic to booked revenue.",
    features: ["Unified coverage", "Voice + chat", "Automation included", "Single system reporting"],
    useCases: ["Growing teams", "Multiple acquisition channels", "Multi-step revenue journeys"],
    howItWorks: ["Choose the bundle", "Enable the connected workflows", "Track the entire funnel in one place"],
    related: ["/features/workflow-automation", "/pricing/enterprise", "/company/book-demo"],
  },
  {
    slug: "enterprise",
    title: "Enterprise Pricing",
    summary: "Support larger teams with governance, onboarding, and rollout flexibility for complex deployments.",
    problem: "Enterprise buyers need more than software; they need alignment, process, and support.",
    solution: "Omniweb enterprise pricing is designed for cross-team deployments, custom workflows, and steady expansion.",
    valueToIndustry: "The industry gets a scalable AI revenue platform that can serve multi-team environments.",
    valueToUser: "Your organization gets a more controlled and adaptable rollout path.",
    outcome: "A predictable path to scaling across teams, business units, or regions.",
    features: ["Governance support", "Custom onboarding", "Scaled rollouts", "Dedicated planning"],
    useCases: ["Multi-location rollouts", "Cross-team operations", "Higher-security environments"],
    howItWorks: ["Assess the rollout needs", "Define the workflow boundaries", "Launch in phases and optimize"],
    related: ["/company/contact", "/resources/security", "/solutions/ai-agency"],
  },
  {
    slug: "shopify",
    title: "Shopify Pricing",
    summary: "Price ecommerce coverage that helps shoppers buy faster and recover more carts.",
    problem: "Ecommerce conversion depends on rapid answers and friction-free product guidance.",
    solution: "Shopify pricing reflects the value of having an AI sales assistant on the storefront.",
    valueToIndustry: "The industry gets a store-first plan that prioritizes conversion over passive support.",
    valueToUser: "Store owners can deploy a more complete shopping experience with less manual work.",
    outcome: "More product questions get answered and more buyers reach checkout.",
    features: ["Storefront coverage", "Cart recovery", "Product Q&A", "Conversion insights"],
    useCases: ["DTC storefronts", "Product launches", "High-SKU catalogs"],
    howItWorks: ["Connect the shop context", "Enable the assistant", "Measure revenue impact"],
    related: ["/solutions/shopify-ai-assistant", "/features/website-knowledge-base", "/company/book-demo"],
  },
  {
    slug: "agency",
    title: "Agency Pricing",
    summary: "Package multi-client deployment and management for agencies delivering Omniweb as a service.",
    problem: "Agencies need a repeatable way to deliver value without rebuilding the stack each time.",
    solution: "Agency pricing supports reuse, client management, and the operational needs of a service business.",
    valueToIndustry: "The industry gets a stronger productized service model for AI deployment.",
    valueToUser: "Your team can manage more clients without multiplying the manual workload.",
    outcome: "Cleaner margins and faster delivery across accounts.",
    features: ["Multi-client support", "Reusable delivery patterns", "Client reporting", "Operational efficiency"],
    useCases: ["White-label services", "Managed AI retainers", "Client onboarding"],
    howItWorks: ["Choose the client model", "Deploy the reusable workflow", "Monitor and optimize outcomes"],
    related: ["/solutions/ai-agency", "/resources/compare", "/company/contact"],
  },
  {
    slug: "faq",
    title: "Pricing FAQ",
    summary: "Get clear answers about setup, usage, support, and how Omniweb fits into your workflow.",
    problem: "Pricing questions can slow decisions when the buyer needs more than a price list.",
    solution: "The FAQ gives clear guidance on how the platform is packaged, deployed, and supported.",
    valueToIndustry: "The market gets a more transparent and predictable buying experience.",
    valueToUser: "Your team can answer common objections and move the decision forward faster.",
    outcome: "Fewer pricing unknowns and more confident next steps.",
    features: ["Setup questions", "Usage guidance", "Support answers", "Plan selection help"],
    useCases: ["Purchase evaluation", "Internal approval", "Implementation planning"],
    howItWorks: ["Read the pricing question", "Review the answer", "Move to the right plan or demo"],
    related: ["/pricing/combo", "/company/book-demo", "/company/contact"],
  },
] as const

export const pricingPages: Record<string, PageEntry> = Object.fromEntries(
  pricingSeeds.map((seed) => [
    seed.slug,
    buildPageEntry({
      sectionLabel: "PRICING",
      primaryAction: primary,
      secondaryAction: secondary,
      footerEyebrow: "Need the right plan for your team?",
      footerTitle: "Choose the package that matches your channels, lead volume, and workflow complexity.",
      footerDescription: "Pricing is designed to make the value of AI coverage easy to understand, compare, and deploy.",
      seed,
      stats: [
        { value: "5", label: "Plan types" },
        { value: "24/7", label: "Coverage" },
        { value: "1", label: "System" },
        { value: "0", label: "Guesswork" },
      ],
    }),
  ])
) as Record<string, PageEntry>
