import { buildPageEntry, type PageEntry } from "@/lib/marketing-page-data"

const primary = { label: "Explore Resources", href: "/resources" }
const secondary = { label: "Book a Demo", href: "/company/book-demo" }

const resourceSeeds = [
  {
    slug: "blog",
    title: "Omniweb Blog",
    summary: "Practical insights on AI-powered sales, lead generation, and customer communication for modern businesses.",
    overview: [
      "The Omniweb Blog is where our team publishes what we are learning from thousands of AI deployments across industries. Every article is written from first-hand experience with real businesses — the patterns that drive results, the mistakes that cost leads, and the strategies that separate high-performing AI deployments from the ones that stall.",
      "We cover the full spectrum of AI in business: how voice AI is changing inbound call handling, how chat assistants are closing the gap between traffic and revenue, how multilingual AI is opening new market segments, and how workflow automation is reducing the operational tax on growing teams. Each post is grounded in data from real use cases rather than abstract theory.",
      "Whether you are a business owner evaluating AI for the first time, a marketing director looking for ways to improve lead conversion, or an operations leader trying to reduce the manual overhead of customer communication, you will find actionable content that applies directly to your situation.",
      "We publish several times a week, and our most popular series — The AI Revenue Playbook, Industry Breakdowns, and Feature Deep Dives — are available in full on the blog. Subscribe to receive new articles as they are published.",
    ],
    problem: "Most content about AI in business is either too theoretical to be actionable or too vendor-specific to be trustworthy. Business owners and operators need practical, experience-based guidance on what AI actually does for real businesses.",
    solution: "The Omniweb Blog publishes honest, practical content based on real deployment experience — covering strategy, tactics, feature breakdowns, and industry applications in a format that is immediately useful to the people running real businesses.",
    valueToIndustry: "Better-informed business owners make better AI deployment decisions. Content that builds genuine understanding of AI capabilities and limitations improves outcomes across the ecosystem.",
    valueToUser: "You learn from the patterns we see across thousands of deployments without having to experiment yourself. You arrive at decisions faster and implement more effectively because you have context.",
    outcome: "More informed decisions, faster implementation, and better AI deployment outcomes from businesses that understand what they are building and why.",
    features: [
      "Practical how-to guides for AI deployment",
      "Industry-specific use case breakdowns",
      "Feature deep dives and configuration best practices",
      "Data-driven performance benchmarks from real deployments",
      "Strategy pieces on AI-first customer communication",
      "Product updates and new feature announcements",
      "Case study write-ups from customer deployments",
      "Email newsletter with curated weekly reading",
    ],
    useCases: [
      "Business owners researching AI before making a platform decision",
      "Marketing directors looking for conversion rate improvement strategies",
      "Operations leaders evaluating AI workflow automation options",
      "Sales teams exploring AI-assisted lead qualification approaches",
      "Agency owners learning how to package AI for client deployments",
    ],
    howItWorks: [
      "Browse articles by category, industry, or feature area using the navigation on the blog index. Use the search to find content on a specific topic.",
      "Subscribe to the newsletter to receive new articles and curated weekly reading in your inbox. No spam — just content we think is worth your time.",
      "Save articles you want to return to, share with your team, or download the guides that are available in PDF format for offline reference.",
    ],
    faq: [
      { question: "How often is the blog updated?", answer: "We publish multiple times per week. Longer strategy pieces and deep dives appear monthly. Subscribe to the newsletter to make sure you do not miss anything." },
      { question: "Can I contribute a guest post?", answer: "We occasionally publish perspectives from practitioners and partners. If you have a topic that is relevant to our audience and grounded in real experience, reach out to our content team." },
    ],
    related: ["/resources/case-studies", "/resources/guides", "/resources/docs"],
  },
  {
    slug: "case-studies",
    title: "Case Studies",
    summary: "Real business outcomes from Omniweb deployments — numbers, context, and what actually changed.",
    overview: [
      "Every case study in this library starts from the same place: a real business, a specific problem, and a measurable outcome. We do not publish case studies that only tell the positive story. We include the setup friction, the initial configuration that did not work, and the adjustments that led to the result — because that context is what makes the story useful to you.",
      "Our case studies span the full range of industries and use cases where Omniweb is deployed: local service businesses that went from missing half their after-hours calls to capturing every one of them, e-commerce stores that reduced cart abandonment by a measurable percentage, healthcare practices that cut their no-show rate using automated reminders, and AI agencies that tripled their client throughput using the multi-tenant platform.",
      "The numbers in our case studies are real, specific, and sourced directly from our platform analytics and customer-reported outcomes. Where a customer has asked us not to publish specifics, we use ranges and have them confirm the accuracy of what is published.",
    ],
    problem: "AI vendor claims are common and hard to verify. Business owners evaluating AI platforms need documented, specific examples of what AI actually delivered for businesses similar to theirs — not abstract ROI claims.",
    solution: "Omniweb publishes detailed, honest case studies from real customer deployments with specific numbers, genuine setup context, and confirmed outcomes — giving prospective customers the evidence they need to evaluate fit.",
    valueToIndustry: "Transparent outcome documentation raises the accountability standard for AI vendors and helps businesses make better buying decisions. The whole market improves when real results are documented and public.",
    valueToUser: "You see what businesses like yours actually achieved with Omniweb, in enough detail to assess whether the results are relevant to your situation. You go into the evaluation process with realistic expectations and specific questions.",
    outcome: "Better-informed buying decisions, reduced evaluation time, and higher confidence that the platform you choose has delivered the outcomes you are looking for.",
    features: [
      "Industry-filtered case study library",
      "Specific outcome numbers with business context",
      "Setup and configuration detail for comparable deployments",
      "Before/after metrics from platform analytics",
      "Customer quotes and direct perspectives",
      "Video case study format for select deployments",
      "Downloadable PDF versions for team sharing",
      "Related feature and product documentation links",
    ],
    useCases: [
      "Businesses evaluating Omniweb for a specific industry use case",
      "Executives presenting AI ROI to internal stakeholders",
      "Agency owners showing prospects what the platform has delivered for other clients",
      "Operators comparing deployment approaches for their specific situation",
      "Teams building business cases for AI investment",
    ],
    howItWorks: [
      "Browse case studies by industry, use case, or outcome type. Each case study includes an overview of the business, the specific problem they were solving, the Omniweb configuration they deployed, and the results.",
      "Filter by industry to find examples most relevant to your situation. Compare setup approaches across similar businesses to identify the configuration patterns most likely to work for you.",
      "Share case studies with your team or present them in your evaluation process using the PDF download or direct link.",
    ],
    faq: [
      { question: "Are the numbers in the case studies verified?", answer: "Yes. Every number is sourced from our platform analytics or directly confirmed with the customer. Where a customer has requested ranges rather than specifics, we note that in the case study." },
      { question: "Can I speak with the customers featured in your case studies?", answer: "For select case studies, we can arrange a customer reference conversation. Contact our sales team to request an introduction." },
    ],
    related: ["/resources/blog", "/company/about", "/pricing/enterprise"],
  },
  {
    slug: "docs",
    title: "Documentation",
    summary: "Technical documentation for setting up, configuring, and optimizing your Omniweb deployment.",
    overview: [
      "The Omniweb documentation covers everything from initial account setup to advanced configuration, API integration, and deployment optimization. Every article is written for practitioners — people who are actually configuring the system — not for readers who just want a general overview.",
      "Our docs are organized by workflow: get started, configure your AI assistant, connect your channels, manage your knowledge base, set up automations, integrate with your existing tools, and monitor performance. Each section builds on the previous one so you can work through setup in sequence or jump directly to the area you need.",
      "We maintain the documentation against every platform update. When a feature changes, the documentation changes with it. If you find something that is out of date or unclear, there is a feedback mechanism on every page — and our documentation team reviews those submissions weekly.",
      "The API reference section covers every endpoint, parameter, and authentication requirement for teams building custom integrations or extending the platform programmatically.",
    ],
    problem: "Poorly documented software costs businesses hours of troubleshooting, support tickets, and configuration guesswork. When developers and operators cannot find the answers they need in documentation, they either give up or under-configure the system.",
    solution: "Omniweb maintains comprehensive, up-to-date documentation for every feature, integration, and configuration option — organized so that any user can find what they need quickly and implement it accurately.",
    valueToIndustry: "Well-documented platforms deploy faster, generate fewer support escalations, and achieve better outcomes because users configure them correctly. Good documentation is a force multiplier for every customer.",
    valueToUser: "You configure your AI system correctly the first time, without needing to contact support for answers that should be self-service. Your team can onboard and implement independently.",
    outcome: "Faster initial setup, fewer configuration errors, and less time spent troubleshooting because the information you need is findable and accurate.",
    features: [
      "Step-by-step setup guides for all platform features",
      "API reference with full parameter documentation",
      "Integration guides for CRM, calendar, and telephony platforms",
      "Knowledge base configuration best practices",
      "Webhook and event documentation",
      "Version history and changelog",
      "In-page feedback and correction submission",
      "Search across all documentation from a single bar",
    ],
    useCases: [
      "New customers completing initial platform setup",
      "Developers building custom integrations via the API",
      "Operators configuring advanced qualification flows",
      "Teams troubleshooting a specific feature or behavior",
      "Agencies setting up client accounts using documented best practices",
    ],
    howItWorks: [
      "Use the search bar to find documentation for any feature, integration, or configuration question. The search covers all articles and returns results ranked by relevance.",
      "Follow the Getting Started guide for a structured walkthrough of the initial setup process. Each article includes the prerequisite steps and links to related configuration options.",
      "Use the API reference for technical integration work. Every endpoint includes a description, parameter list, authentication requirements, and example requests and responses.",
    ],
    faq: [
      { question: "How do I report a documentation error?", answer: "Every documentation page has a 'Was this helpful?' feedback section at the bottom. You can flag errors, suggest improvements, or ask questions directly from the page." },
      { question: "Is there documentation in languages other than English?", answer: "The primary documentation is in English. Key setup guides are available in Spanish and French. We are expanding language coverage based on customer demand." },
    ],
    related: ["/resources/help-center", "/resources/api", "/company/contact"],
  },
  {
    slug: "help-center",
    title: "Help Center",
    summary: "Answers to common questions, troubleshooting guides, and support for every stage of your deployment.",
    overview: [
      "The Omniweb Help Center is the first place to look when something is not working as expected, when you want to understand a feature more deeply, or when you need guidance on a specific configuration challenge. It is designed to answer the questions that come up in the normal course of using the platform — quickly, clearly, and without requiring a support ticket.",
      "The Help Center is organized around the things people actually get stuck on: how the AI learns from your knowledge base, why a specific automation is not triggering, how to interpret your conversation analytics, and how to configure integrations with specific third-party tools. Articles include screenshots, configuration examples, and decision trees for common troubleshooting scenarios.",
      "When the Help Center does not have what you need, the contact support option connects you to a human support specialist. Response time for support tickets averages under four hours for standard issues and under one hour for platform-affecting incidents.",
    ],
    problem: "Support tickets are expensive for vendors and time-consuming for customers. Most support questions have documented answers that are not being found because the search is poor, the organization is confusing, or the content is out of date.",
    solution: "Omniweb maintains a well-organized, searchable Help Center that answers the questions customers actually ask — reducing the time from question to answer and decreasing the support ticket volume for issues that can be self-served.",
    valueToIndustry: "Effective self-service support is a major quality-of-life improvement for software users. When help is findable and accurate, customers move faster and feel more confident in the platform.",
    valueToUser: "You get answers to common questions immediately, without waiting for a support response. When you do need human help, the support team has better context because you have already worked through the self-service options.",
    outcome: "Faster resolution for common issues. Less time spent waiting for support responses. More confidence in your ability to configure and operate the platform independently.",
    features: [
      "Searchable article library organized by topic and feature",
      "Step-by-step troubleshooting guides with screenshots",
      "Video walkthroughs for complex configuration tasks",
      "Common error messages explained with resolution steps",
      "Integration-specific FAQ sections",
      "Direct support ticket submission from any article",
      "Live chat availability during business hours",
      "Status page link for platform health monitoring",
    ],
    useCases: [
      "Operators troubleshooting a configuration that is not working as expected",
      "New customers working through initial setup questions",
      "Teams trying to understand a specific platform behavior or output",
      "Developers looking for guidance on a specific API behavior",
      "Administrators managing account settings and permissions",
    ],
    howItWorks: [
      "Search for your question using the search bar at the top of the Help Center. Enter the feature name, the error message, or a description of what you are trying to do.",
      "Browse articles by category if you prefer to explore. Categories are organized around the main workflow areas of the platform.",
      "If you cannot find what you need, submit a support ticket from the Contact Support button on any page. Your account context is included automatically so the support team can help faster.",
    ],
    faq: [
      { question: "What are the support response time expectations?", answer: "Standard support tickets are responded to within four business hours. Platform-affecting issues are escalated and responded to within one hour. Enterprise customers have access to priority support with shorter response windows." },
      { question: "Is live chat available?", answer: "Yes, live chat is available Monday through Friday during business hours. Outside of those hours, the chat will offer to submit a support ticket on your behalf." },
    ],
    related: ["/resources/docs", "/resources/api", "/company/contact"],
  },
  {
    slug: "integrations",
    title: "Integrations",
    summary: "Connect Omniweb to your existing tools — CRM, calendar, telephony, and more.",
    overview: [
      "The most powerful AI deployment is one that works inside your existing business infrastructure, not alongside it. When Omniweb connects to your CRM, leads are logged automatically without manual entry. When it connects to your calendar, appointments are booked in real time without back-and-forth coordination. When it connects to your telephony system, every call is answered and processed without requiring a separate intake workflow.",
      "Omniweb integrates with the tools that businesses already use: HubSpot, Salesforce, Zoho, GoHighLevel, and other CRM platforms; Google Calendar, Calendly, Acuity, and other scheduling tools; Twilio, SignalWire, and other telephony providers; Shopify and other e-commerce platforms; Slack, email, and webhook-based notification systems.",
      "Each integration is built and maintained by the Omniweb team. When the connected platform updates its API, we update our integration. The configuration is designed to be set up by a non-developer — most integrations are connected through an authenticated OAuth flow or an API key, not a custom code project.",
      "For businesses with custom internal systems, the Omniweb API provides the hooks needed to build integrations that fit your specific architecture. The same data that flows through our native integrations is available through the API.",
    ],
    problem: "AI platforms that do not integrate with existing business systems create data silos, manual reconciliation work, and adoption friction. A lead that is captured by AI but not automatically synced to the CRM is a lead that gets lost in the handoff.",
    solution: "Omniweb provides native integrations with the most common business tools and an API for custom connections — ensuring that AI-captured data flows into the right systems automatically without manual work.",
    valueToIndustry: "Connected AI systems deliver more value because the data they capture is immediately usable across the business. Integration is not an add-on; it is the difference between a useful tool and a transformative one.",
    valueToUser: "Leads are logged in your CRM automatically. Appointments appear in your calendar immediately. Your team works with one unified view of the data rather than reconciling multiple systems.",
    outcome: "Zero manual data entry for AI-captured leads and bookings. Full visibility into AI performance within your existing reporting tools. Faster response times because data is where your team expects it.",
    features: [
      "HubSpot, Salesforce, and Zoho CRM native integrations",
      "Google Calendar and Calendly booking integrations",
      "Twilio and SignalWire telephony integrations",
      "Shopify and WooCommerce e-commerce integrations",
      "GoHighLevel native integration",
      "Webhook support for custom event routing",
      "Zapier and Make compatibility for no-code automation",
      "REST API with full authentication and documentation",
    ],
    useCases: [
      "Sales teams syncing AI-captured leads directly into their CRM pipeline",
      "Service businesses connecting booking to their calendar and dispatch system",
      "E-commerce stores integrating AI with their order management platform",
      "Marketing teams routing leads into email nurture workflows automatically",
      "Developers building custom integrations with internal business systems",
    ],
    howItWorks: [
      "Navigate to the Integrations section of your Omniweb dashboard. Select the platform you want to connect and authenticate using OAuth or an API key.",
      "Configure the field mapping to specify how Omniweb data maps to your connected platform's data model. Most integrations have sensible defaults that work without customization.",
      "Test the integration with a sample lead or booking to confirm data is flowing correctly, then enable it for live traffic.",
    ],
    faq: [
      { question: "Do I need a developer to set up integrations?", answer: "Most integrations are set up through a guided OAuth or API key flow that does not require coding. Custom integrations using the API do require developer access." },
      { question: "What happens if the connected platform is down?", answer: "Omniweb queues integration events during connected platform outages and retries them when connectivity is restored. No data is lost during temporary outages." },
    ],
    related: ["/features/crm-integrations", "/resources/api", "/resources/docs"],
  },
  {
    slug: "security",
    title: "Security",
    summary: "How Omniweb protects your data, your conversations, and your business.",
    overview: [
      "When you deploy AI on the front lines of your customer communication, you are trusting that platform with sensitive conversations, contact information, and in some cases, protected health information or financial data. Security is not a feature we describe in a marketing context — it is a set of engineering and operational practices we are responsible for and accountable to.",
      "Omniweb is built on SOC 2 Type II compliant infrastructure. Conversation data is encrypted in transit and at rest. Access to production systems is restricted, audited, and requires multi-factor authentication. Our data retention policies give customers control over how long conversation data is stored and what can be accessed by Omniweb staff.",
      "We conduct regular penetration testing through third-party security firms and publish the scope and outcomes of those assessments to enterprise customers under NDA. Our security posture is not static — we maintain an active security roadmap and update our practices as the threat landscape evolves.",
      "For customers in regulated industries — healthcare, finance, legal — we have specific compliance documentation and contractual arrangements that address the requirements of HIPAA, SOC 2, GDPR, and CCPA. Contact our compliance team to review the specific documentation for your regulatory context.",
    ],
    problem: "Businesses deploying AI on customer-facing channels need confidence that their data and their customers' data is protected. Security claims without documentation are not sufficient for regulated industries or enterprise customers.",
    solution: "Omniweb provides documented security practices, SOC 2 Type II compliance, encryption standards, access controls, and compliance-specific contractual arrangements for customers in regulated industries.",
    valueToIndustry: "High security standards across AI platforms protect both businesses and the customers whose data flows through these systems. The industry benefits when security is a requirement rather than an afterthought.",
    valueToUser: "You can deploy Omniweb on customer-facing channels with confidence that your data is protected, your customers' information is handled appropriately, and your regulatory obligations are supported.",
    outcome: "Compliant AI deployment without the custom engineering work. Documented security posture for enterprise procurement reviews. Regulatory-specific contractual coverage for healthcare, finance, and legal deployments.",
    features: [
      "SOC 2 Type II compliant infrastructure",
      "End-to-end encryption for all conversation data",
      "Multi-factor authentication for all platform access",
      "Role-based access control and audit logging",
      "Configurable data retention policies",
      "HIPAA-supportive configuration for healthcare deployments",
      "GDPR and CCPA compliance documentation",
      "Regular third-party penetration testing",
    ],
    useCases: [
      "Healthcare organizations evaluating HIPAA compliance for patient communication AI",
      "Financial services firms assessing data security for client-facing deployments",
      "Enterprise procurement teams reviewing security documentation for vendor approval",
      "Legal firms evaluating data handling for client communication AI",
      "Businesses processing personal data under GDPR or CCPA",
    ],
    howItWorks: [
      "Review the security documentation in this section to understand our general security posture, data handling practices, and compliance certifications.",
      "For regulated industry deployments, contact our compliance team to receive the relevant compliance documentation and to discuss contractual arrangements.",
      "Enterprise customers can request the SOC 2 Type II report, penetration test summaries, and our data processing addendum through their account manager.",
    ],
    faq: [
      { question: "Is Omniweb HIPAA compliant?", answer: "Omniweb supports HIPAA-compliant deployments with appropriate data handling configuration and contractual arrangements including a Business Associate Agreement (BAA). Contact our compliance team to review the specific requirements." },
      { question: "Where is conversation data stored?", answer: "Conversation data is stored in US-based data centers by default. EU-based storage is available for customers with GDPR data residency requirements." },
    ],
    related: ["/resources/docs", "/company/about", "/pricing/enterprise"],
  },
  {
    slug: "api",
    title: "API Reference",
    summary: "Full REST API documentation for developers building integrations, custom workflows, and extensions on Omniweb.",
    overview: [
      "The Omniweb API gives developers programmatic access to every capability of the platform: creating and managing AI assistant configurations, ingesting knowledge base content, triggering conversation flows, accessing conversation logs, managing contacts, and pulling analytics data. Everything the dashboard does is available through the API.",
      "The API is REST-based with JSON request and response bodies, standard HTTP status codes, and bearer token authentication. Rate limits are generous and tier-based. Webhooks are available for all significant platform events, allowing external systems to react to conversation outcomes in real time.",
      "The API reference in this section documents every endpoint, parameter, authentication method, error code, and example request and response. It is generated directly from our internal specification and is kept in sync with every platform release.",
      "For developers who prefer a hands-on starting point, our API quickstart guide walks through authentication, a first knowledge base ingestion, a test conversation trigger, and a webhook handler in under thirty minutes.",
    ],
    problem: "AI platforms that cannot be accessed programmatically are not viable for enterprise or technical buyers who need to integrate with existing systems, automate configuration changes, or build custom workflows on top of the platform.",
    solution: "Omniweb provides a comprehensive REST API that covers all platform capabilities, with full documentation, webhook support, and a generous rate limit structure — giving developers everything they need to build reliable, production-grade integrations.",
    valueToIndustry: "Programmable AI platforms can be embedded into business systems and workflows in ways that closed platforms cannot. The API is what allows Omniweb to become a platform rather than just a product.",
    valueToUser: "Your development team can integrate Omniweb with your existing systems, automate configuration changes at scale, build custom workflows on top of our AI capabilities, and pull platform data into your own analytics and reporting infrastructure.",
    outcome: "Omniweb embedded in your existing business systems without manual reconciliation. Custom workflows built on our AI capabilities. Platform data in your reporting tools.",
    features: [
      "Full CRUD access to AI assistant configurations",
      "Knowledge base content ingestion and management endpoints",
      "Contact and conversation record access",
      "Real-time webhook events for all platform outcomes",
      "Analytics data export with filterable query parameters",
      "OAuth 2.0 and API key authentication",
      "Detailed error codes with resolution guidance",
      "Rate limiting documentation with tier-based limits",
    ],
    useCases: [
      "Developers building CRM integrations that sync AI-captured leads",
      "Operations engineers automating knowledge base updates from internal content systems",
      "Analytics engineers pulling platform data into internal BI tools",
      "SaaS builders using Omniweb as an AI infrastructure layer",
      "Agency platforms automating client account setup and configuration",
    ],
    howItWorks: [
      "Authenticate using your API key from the Omniweb dashboard. Include the bearer token in the Authorization header of every request.",
      "Use the endpoint reference to find the specific API call you need. Every endpoint includes a parameter table, example request, and example response.",
      "Set up webhooks from your dashboard to receive real-time event notifications for conversation completions, lead captures, bookings, and other platform events.",
    ],
    faq: [
      { question: "What are the API rate limits?", answer: "Rate limits depend on your plan tier. Standard plans support up to 1,000 requests per minute. Enterprise plans have higher limits available on request. Rate limit details are documented in the API reference." },
      { question: "Is there a sandbox environment for testing?", answer: "Yes. Every account has a sandbox environment that mirrors the production API but does not send real messages or process real conversations. Use the sandbox for development and testing before deploying to production." },
    ],
    related: ["/resources/docs", "/resources/integrations", "/resources/security"],
  },
  {
    slug: "guides",
    title: "Guides",
    summary: "Step-by-step playbooks for common AI deployment scenarios — strategy, setup, and optimization.",
    overview: [
      "The Omniweb Guides library is where we document the deployment playbooks our team has developed across thousands of real implementations. Each guide is a complete, opinionated walkthrough of a specific deployment scenario — not a general introduction to the technology, but a specific set of steps for getting a specific type of result.",
      "Guides are organized by goal: 'Set up after-hours call handling for a home services business,' 'Launch a cart abandonment recovery campaign for your Shopify store,' 'Configure a lead qualification flow for a real estate team,' 'Build a patient intake system for a healthcare practice.' Each guide includes the configuration decisions you will need to make, the rationale behind the recommended approach, and the metrics to watch after launch.",
      "We update guides based on what we learn from customer deployments. When a new pattern consistently outperforms the previous recommendation, the guide is updated. The publication date and revision history are visible on every guide page.",
    ],
    problem: "Most AI documentation explains what you can do but not how to do it well for a specific outcome. Business operators need opinionated, practical playbooks for common deployment scenarios — not just a list of features.",
    solution: "The Omniweb Guides library provides complete, step-by-step deployment playbooks organized by business goal and industry — with specific configuration recommendations, rationale, and performance benchmarks.",
    valueToIndustry: "Documented deployment playbooks reduce the time from purchase decision to working AI system. When businesses deploy correctly the first time, they see results faster and develop more confidence in the platform.",
    valueToUser: "You deploy your AI system correctly the first time, following a playbook that has been proven across many similar businesses. You avoid the configuration mistakes that commonly delay results.",
    outcome: "Faster time to a working deployment. Higher configuration quality on the first attempt. Better initial performance because you are following a pattern that has worked for businesses like yours.",
    features: [
      "Goal-oriented deployment playbooks by industry and use case",
      "Configuration decision trees with recommended choices",
      "Before and after performance benchmark expectations",
      "Troubleshooting sections for common setup issues",
      "Video companion guides for visual learners",
      "Downloadable configuration templates",
      "Revision history showing how recommendations have evolved",
      "Related guides and documentation links in each article",
    ],
    useCases: [
      "New customers completing their first AI deployment following a proven playbook",
      "Operators adding a new channel or feature to an existing deployment",
      "Agencies using guides as the foundation for client deployment documentation",
      "Teams optimizing an existing deployment that is not performing as expected",
      "Business owners evaluating whether a specific deployment scenario fits their situation",
    ],
    howItWorks: [
      "Browse guides by industry or goal to find the one that matches your deployment scenario. Read the overview section to confirm it applies to your situation before diving in.",
      "Follow the steps in sequence. Each step includes the specific configuration action, the setting to use, and a brief explanation of why this choice works.",
      "After going live, use the performance benchmarks in the guide to assess whether your deployment is tracking as expected and which optimizations to try first.",
    ],
    faq: [
      { question: "How are the guides kept up to date?", answer: "Our team reviews guides quarterly and updates them when deployment patterns, platform features, or best practices change. The revision date is visible at the top of every guide." },
      { question: "Can I suggest a guide topic?", answer: "Yes. We track guide requests and prioritize based on demand. Submit a guide request from the Help Center or through our community forum." },
    ],
    related: ["/resources/docs", "/resources/blog", "/resources/case-studies"],
  },
]

export const resourcePages: Record<string, PageEntry> = Object.fromEntries(
  resourceSeeds.map((seed) => [
    seed.slug,
    buildPageEntry({
      sectionLabel: "RESOURCES",
      primaryAction: primary,
      secondaryAction: secondary,
      footerEyebrow: "Ready to see it in action?",
      footerTitle: "Every resource points toward one outcome: AI that works for your business.",
      footerDescription: "Guides, docs, case studies, and integrations — all designed to help you deploy faster and get results sooner.",
      seed,
      stats: [
        { value: "100+", label: "Help articles" },
        { value: "50+", label: "Integration guides" },
        { value: "30+", label: "Case studies" },
        { value: "8", label: "Resource types" },
      ],
    }),
  ])
) as Record<string, PageEntry>
