import { buildPageEntry, type PageEntry } from "@/lib/marketing-page-data"

const primary = { label: "Get Started", href: "/get-started" }
const secondary = { label: "Book a Demo", href: "/company/book-demo" }

const resourceSeeds = [
  {
    slug: "blog",
    title: "Blog",
    summary: "Read practical posts on AI revenue systems, conversion strategy, and workflow design.",
    problem: "Teams often know they need more conversions but lack a repeatable plan to get there.",
    solution: "Omniweb's blog turns product ideas and operator lessons into clear, actionable guidance.",
    valueToIndustry: "The industry gets a steady stream of education that helps teams deploy AI with confidence.",
    valueToUser: "Readers get straight answers, examples, and rollout ideas they can use immediately.",
    outcome: "Faster decision-making and fewer blind spots when planning a launch.",
    features: ["Strategic articles", "Launch breakdowns", "Operator insights", "Practical examples"],
    useCases: ["Research before implementation", "Team training", "Ongoing optimization ideas"],
    howItWorks: ["Pick the topic", "Learn the playbook", "Apply it to your rollout"],
    related: ["/resources/guides", "/resources/case-studies", "/features/lead-automation"],
  },
  {
    slug: "case-studies",
    title: "Case Studies",
    summary: "See how businesses use Omniweb to improve response speed, lead quality, and bookings.",
    problem: "It is hard to evaluate a platform without seeing real-world outcomes.",
    solution: "Our case studies show the before-and-after story of AI revenue systems in action.",
    valueToIndustry: "The market gets proof that AI can improve both service and sales outcomes.",
    valueToUser: "Decision-makers can evaluate fit faster and with more confidence.",
    outcome: "Less guesswork and more evidence-driven buying decisions.",
    features: ["Before/after outcomes", "Industry-specific stories", "Operational context", "Deployment lessons"],
    useCases: ["Buyer education", "Internal approval", "Sales enablement"],
    howItWorks: ["Review the business challenge", "See the deployment details", "Compare the outcomes to your goals"],
    related: ["/resources/blog", "/resources/compare", "/solutions/shopify-ai-assistant"],
  },
  {
    slug: "docs",
    title: "Docs",
    summary: "Implementation docs and product reference material for teams building with Omniweb.",
    problem: "Great software still needs clear instructions to deploy and maintain well.",
    solution: "The docs give your team a structured way to understand setup, workflows, and core behavior.",
    valueToIndustry: "The industry gets a clearer path from evaluation to deployment.",
    valueToUser: "Your team can move faster with fewer questions during setup.",
    outcome: "Less friction during implementation and a better chance of going live quickly.",
    features: ["Setup references", "Product behavior notes", "Workflow guidance", "Launch checklists"],
    useCases: ["Technical onboarding", "Support handoff", "Internal team training"],
    howItWorks: ["Find the relevant doc", "Follow the implementation steps", "Validate the result in your own environment"],
    related: ["/resources/guides", "/resources/api", "/company/status"],
  },
  {
    slug: "help-center",
    title: "Help Center",
    summary: "Get fast answers for setup, billing, and product usage without digging through support queues.",
    problem: "Support questions slow teams down when the answer should be easy to find.",
    solution: "The help center gives you concise answers and a clear place to start when something needs attention.",
    valueToIndustry: "The industry gets a support experience that respects time and reduces frustration.",
    valueToUser: "Users can solve common issues on their own and move on quickly.",
    outcome: "Fewer support delays and a smoother experience for new and existing customers.",
    features: ["Quick answers", "Setup troubleshooting", "Billing guidance", "Usage help"],
    useCases: ["Self-serve support", "Onboarding questions", "Admin troubleshooting"],
    howItWorks: ["Search the question", "Read the relevant article", "Take the next step or contact support"],
    related: ["/resources/docs", "/company/contact", "/company/status"],
  },
  {
    slug: "integrations",
    title: "Integrations",
    summary: "Connect Omniweb to the systems your team already uses for CRM, follow-up, and operations.",
    problem: "Disconnected tools force teams to rebuild the same workflow across multiple platforms.",
    solution: "Omniweb integrates with your stack so the conversation can trigger the rest of the system.",
    valueToIndustry: "The industry gets a cleaner bridge between front-end interaction and back-end execution.",
    valueToUser: "Your team keeps the tools they know while gaining an AI front-end that plugs in cleanly.",
    outcome: "Less duplicate work and a smoother handoff from conversation to action.",
    features: ["CRM sync", "Webhook support", "Task creation", "Follow-up triggers"],
    useCases: ["GoHighLevel workflows", "Custom integrations", "Notification routing"],
    howItWorks: ["Capture the event", "Map it to your systems", "Keep the workflow synchronized"],
    related: ["/features/crm-integrations", "/features/workflow-automation", "/pricing/enterprise"],
  },
  {
    slug: "security",
    title: "Security",
    summary: "Review the security practices that support a multi-tenant AI revenue platform.",
    problem: "Businesses need confidence that customer conversations and data stay protected.",
    solution: "Omniweb is built to support controlled access, responsible handling, and operational transparency.",
    valueToIndustry: "The industry gets a clearer security story for AI-powered customer interactions.",
    valueToUser: "Your team can evaluate the platform with a more confident view of risk and governance.",
    outcome: "Better trust in how data, access, and customer interactions are handled.",
    features: ["Access controls", "Data handling practices", "Operational transparency", "Tenant-aware architecture"],
    useCases: ["Security reviews", "Vendor approval", "Compliance conversations"],
    howItWorks: ["Understand the platform boundaries", "Review the controls", "Move forward with an informed decision"],
    related: ["/company/privacy", "/company/terms", "/company/status"],
  },
  {
    slug: "api",
    title: "API",
    summary: "Build custom workflows and connect Omniweb to the systems your team already operates.",
    problem: "Sometimes a business needs a tailored automation path that goes beyond the UI.",
    solution: "The Omniweb API makes it possible to extend the platform and wire the conversation engine into your stack.",
    valueToIndustry: "The industry gets a more flexible way to deploy AI revenue workflows.",
    valueToUser: "Developers and operators can tailor the system to the exact business process.",
    outcome: "More control over the deployment and a better fit for custom environments.",
    features: ["Programmatic access", "Workflow triggers", "Custom integrations", "Extensible deployment"],
    useCases: ["Internal tooling", "Productized services", "Tailored lead routing"],
    howItWorks: ["Identify the event", "Call the API or hook", "Trigger the right action downstream"],
    related: ["/resources/docs", "/features/workflow-automation", "/company/contact"],
  },
  {
    slug: "guides",
    title: "Guides",
    summary: "Follow step-by-step rollout guides for scripts, launches, and optimization ideas.",
    problem: "Teams often need a clear plan before they can launch a new revenue system.",
    solution: "The guides break the rollout into practical steps so launch feels manageable and measurable.",
    valueToIndustry: "The market gets a more approachable path to deploying AI conversion tools.",
    valueToUser: "Your team can move with confidence and less ambiguity.",
    outcome: "A smoother launch and fewer missed details along the way.",
    features: ["Launch checklists", "Script templates", "Optimization ideas", "Role-based advice"],
    useCases: ["New site launches", "AI assistant rollout", "Team training"],
    howItWorks: ["Pick the right guide", "Follow the setup steps", "Measure and refine"],
    related: ["/resources/blog", "/resources/docs", "/solutions/ai-agency"],
  },
  {
    slug: "compare",
    title: "Compare",
    summary: "See how Omniweb compares with manual processes, point tools, and disconnected systems.",
    problem: "Teams waste time comparing a patchwork of tools that do only one part of the job.",
    solution: "Omniweb combines voice, chat, qualification, automation, and follow-up into one system.",
    valueToIndustry: "The industry gets a simpler model for evaluating revenue tooling.",
    valueToUser: "Buyers can compare outcomes, not just features.",
    outcome: "A clearer decision process and better platform fit.",
    features: ["Outcome comparison", "Workflow breadth", "Deployment clarity", "Feature-to-value mapping"],
    useCases: ["Vendor evaluation", "Stakeholder reviews", "Replacement planning"],
    howItWorks: ["Compare the workflows", "Review the outcomes", "Choose the platform that handles more of the revenue path"],
    related: ["/resources/case-studies", "/pricing/combo", "/solutions/ai-agency"],
  },
] as const

export const resourcePages: Record<string, PageEntry> = Object.fromEntries(
  resourceSeeds.map((seed) => [
    seed.slug,
    buildPageEntry({
      sectionLabel: "RESOURCES",
      primaryAction: primary,
      secondaryAction: secondary,
      footerEyebrow: "Need a deeper walkthrough?",
      footerTitle: "Read, compare, and book a demo when you're ready to move from research to launch.",
      footerDescription: "The resource library is built to help teams evaluate Omniweb with less friction and more context.",
      seed,
      stats: [
        { value: "9", label: "Resource hubs" },
        { value: "1", label: "Library" },
        { value: "24/7", label: "Access" },
        { value: "0", label: "Guesswork" },
      ],
    }),
  ])
) as Record<string, PageEntry>
