import { buildPageEntry, type PageEntry } from "@/lib/marketing-page-data"

const primary = { label: "Book a Demo", href: "/company/book-demo" }
const secondary = { label: "Install AI Agent", href: "/dashboard/widget-install" }

const solutionSeeds = [
  {
    slug: "shopify-ai-assistant",
    title: "Shopify AI Assistant",
    summary: "Help shoppers find products, answer pre-purchase questions, and recover revenue before they abandon the cart.",
    problem: "Online stores lose sales when customers cannot get instant answers about product fit, shipping, or trust.",
    solution: "Omniweb adds an intelligent store assistant that guides buyers, resolves objections, and nudges them toward checkout.",
    valueToIndustry: "The ecommerce industry gets a front-end sales assistant that supports conversion instead of just support.",
    valueToUser: "Store teams get fewer repetitive questions and more qualified shoppers moving through the funnel.",
    outcome: "More carts are recovered, more questions are answered, and more visitors become buyers.",
    features: ["Product question handling", "Cart recovery flows", "Store knowledge answers", "Purchase-intent routing"],
    useCases: ["DTC storefronts", "High-SKU catalogs", "Upsell and cross-sell journeys"],
    howItWorks: ["Detect store intent", "Answer from product and policy knowledge", "Route the shopper to the right conversion step"],
    related: ["/features/ai-chat-assistants", "/features/website-knowledge-base", "/pricing/shopify"],
  },
  {
    slug: "local-service-businesses",
    title: "Local Service Businesses",
    summary: "Turn local traffic and inbound calls into booked jobs, cleaner intake, and faster follow-up.",
    problem: "Service businesses lose momentum when a lead waits for a call back or a quote request goes unanswered.",
    solution: "Omniweb answers, qualifies, and routes the request so busy local teams can focus on the jobs instead of inbox triage.",
    valueToIndustry: "The local service market gets a more reliable intake layer that works across every channel.",
    valueToUser: "Owners and office staff save time while keeping more opportunities in the pipeline.",
    outcome: "More requests get handled quickly, and fewer local leads are lost to delay.",
    features: ["Quote qualification", "Service-area checks", "Fast routing", "Follow-up automation"],
    useCases: ["B2C service requests", "Urgent callbacks", "Peak-season intake"],
    howItWorks: ["Capture the request", "Confirm service fit and urgency", "Route or book the job automatically"],
    related: ["/solutions/contractors", "/features/appointment-scheduling", "/pricing/combo"],
  },
  {
    slug: "contractors",
    title: "Contractors",
    summary: "Help contractors answer after-hours leads, qualify the job, and book more work without more office staff.",
    problem: "Contractors miss calls after hours and lose quote requests when the office is already busy.",
    solution: "Omniweb handles roofing, plumbing, HVAC, and repair inquiries with fast qualification and clear handoff paths.",
    valueToIndustry: "The trades get a dependable response layer that keeps job flow moving all day and night.",
    valueToUser: "Teams spend less time chasing callers and more time on profitable work.",
    outcome: "More booked jobs, faster response times, and fewer missed opportunities.",
    features: ["After-hours lead capture", "Job-type qualification", "Booking and callback routing", "Automated follow-up"],
    useCases: ["Roofing and HVAC", "Plumbing and repair", "Mechanics and roadside jobs"],
    howItWorks: ["Answer the caller", "Qualify service type, urgency, and location", "Route to booking or a callback sequence"],
    related: ["/features/ai-voice-agents", "/features/email-follow-up", "/pricing/ai-telephony"],
  },
  {
    slug: "real-estate",
    title: "Real Estate",
    summary: "Qualify buyers and renters, keep tours moving, and reduce the time between inquiry and showing.",
    problem: "Real estate leads often go cold because the first response is slow or generic.",
    solution: "Omniweb captures intent quickly, routes serious inquiries, and keeps listings tied to a responsive follow-up system.",
    valueToIndustry: "The industry gets a more immediate and scalable intake system for listings and client inquiries.",
    valueToUser: "Agents stay focused on showing property while AI handles the repetitive first questions.",
    outcome: "More inquiries become real conversations, and more of those conversations become appointments.",
    features: ["Buyer qualification", "Tour scheduling", "Listing Q&A", "Lead prioritization"],
    useCases: ["Property inquiries", "Open-house follow-up", "Lease and rental screening"],
    howItWorks: ["Capture property interest", "Ask the right qualification questions", "Book or route to the right agent"],
    related: ["/features/appointment-scheduling", "/features/website-knowledge-base", "/pricing/enterprise"],
  },
  {
    slug: "healthcare",
    title: "Healthcare",
    summary: "Support patient intake, scheduling, reminders, and common questions with a calm, responsive AI layer.",
    problem: "Healthcare teams spend too much time repeating intake details and chasing appointments.",
    solution: "Omniweb can guide visitors through the right next step while keeping communication organized and timely.",
    valueToIndustry: "Healthcare organizations gain an efficient front door that helps staff stay focused on care.",
    valueToUser: "Patients get faster answers and a more predictable path to the appointment or resource they need.",
    outcome: "Lower administrative drag and fewer missed appointments.",
    features: ["Patient intake support", "Reminder workflows", "Question answering", "Routing to the right department"],
    useCases: ["Appointment scheduling", "New patient intake", "Frequently asked questions"],
    howItWorks: ["Capture the request safely", "Guide the patient to the correct next step", "Send reminders and follow-up automatically"],
    related: ["/features/multilingual-ai", "/features/appointment-scheduling", "/pricing/enterprise"],
  },
  {
    slug: "home-services",
    title: "Home Services",
    summary: "Turn home-service inquiries into booked visits with quick answers, routing, and automated follow-up.",
    problem: "Home-service prospects move fast and rarely wait for a slow response.",
    solution: "Omniweb answers the first question, qualifies the service need, and helps the customer take the next step immediately.",
    valueToIndustry: "The home-services market gets a consistent conversion layer across web, phone, and chat.",
    valueToUser: "Teams can focus on work orders while AI keeps the intake queue moving.",
    outcome: "More requests become booked visits instead of lost messages.",
    features: ["Quote requests", "Service-area checks", "Quick routing", "Reminder and follow-up flows"],
    useCases: ["Cleaning and maintenance", "Handyman requests", "Seasonal home projects"],
    howItWorks: ["Capture the service need", "Confirm the right service area and timing", "Book or follow up automatically"],
    related: ["/features/lead-automation", "/features/email-follow-up", "/solutions/local-service-businesses"],
  },
  {
    slug: "ecommerce",
    title: "Ecommerce",
    summary: "Support shopping journeys with instant answers, smart routing, and a conversion-first AI assistant.",
    problem: "Traffic is expensive, and every unanswered question increases the risk of a bounce.",
    solution: "Omniweb helps ecommerce brands answer product questions, reduce hesitation, and guide buyers toward checkout.",
    valueToIndustry: "The ecommerce industry gets a better on-site conversion engine without building a new support stack.",
    valueToUser: "Your team gets more sales-qualified conversations from the same traffic.",
    outcome: "Higher conversion, lower abandonment, and better shopping support.",
    features: ["Product guidance", "Cart recovery", "Store knowledge access", "Conversation summaries"],
    useCases: ["Pre-purchase support", "Cross-sell recommendations", "High-value product pages"],
    howItWorks: ["Understand the page context", "Answer the shopper's question", "Move them toward purchase or follow-up"],
    related: ["/solutions/shopify-ai-assistant", "/features/ai-chat-assistants", "/pricing/shopify"],
  },
  {
    slug: "professional-services",
    title: "Professional Services",
    summary: "Qualify consultations, capture context, and keep client intake organized from the first touch.",
    problem: "Firms lose prospects when the first response is slow or intake questions are repeated by hand.",
    solution: "Omniweb screens visitors, collects the right detail, and helps teams move promising clients toward a consultation.",
    valueToIndustry: "The industry gets a cleaner and more scalable intake process for high-trust services.",
    valueToUser: "Partners and staff spend less time on admin and more time on billable work.",
    outcome: "Better-qualified consultations and a more professional first impression.",
    features: ["Consultation intake", "FAQ handling", "Lead summaries", "Appointment routing"],
    useCases: ["Law firms", "Consultants", "Accounting and advisory"],
    howItWorks: ["Ask the right qualifying questions", "Summarize the case or need", "Book the consultation or route it internally"],
    related: ["/features/lead-automation", "/features/appointment-scheduling", "/pricing/agency"],
  },
  {
    slug: "roadside-assistance",
    title: "Roadside Assistance",
    summary: "Capture urgent dispatch details quickly so help can be routed with less confusion and delay.",
    problem: "In roadside situations, every minute matters and poor intake creates avoidable friction.",
    solution: "Omniweb captures the incident details, confirms the need, and helps the team dispatch the right response.",
    valueToIndustry: "The industry gets a faster, more reliable intake path for urgent requests.",
    valueToUser: "Your customers get a clearer experience when they need help most.",
    outcome: "Less manual triage and a better chance of resolving urgent requests quickly.",
    features: ["Urgent intake", "Location capture", "Dispatch routing", "Follow-up summaries"],
    useCases: ["Tow requests", "Battery issues", "Emergency support"],
    howItWorks: ["Collect location and issue details", "Verify the service need", "Dispatch or escalate immediately"],
    related: ["/features/ai-voice-agents", "/features/lead-automation", "/pricing/ai-telephony"],
  },
  {
    slug: "ai-agency",
    title: "AI Agency",
    summary: "Package, deploy, and manage AI revenue systems for clients with a repeatable delivery model.",
    problem: "Agencies need a faster way to deliver AI value without building every workflow from scratch.",
    solution: "Omniweb gives agencies a platform for multi-tenant deployment, workflow reuse, and measurable outcomes.",
    valueToIndustry: "The agency market gets a productized delivery layer that reduces custom build effort.",
    valueToUser: "Your team can launch more client programs with less operational overhead.",
    outcome: "More deployments, cleaner support, and a better margin on managed AI services.",
    features: ["Multi-tenant deployment", "Reusable workflow patterns", "Client reporting", "Managed handoff"],
    useCases: ["White-label delivery", "Retainer services", "Client onboarding acceleration"],
    howItWorks: ["Choose the client system", "Apply a proven template", "Monitor results and optimize"],
    related: ["/features/workflow-automation", "/resources/compare", "/pricing/agency"],
  },
] as const

export const solutionPages: Record<string, PageEntry> = Object.fromEntries(
  solutionSeeds.map((seed) => [
    seed.slug,
    buildPageEntry({
      sectionLabel: "SOLUTIONS",
      primaryAction: primary,
      secondaryAction: secondary,
      footerEyebrow: "Need a solution tailored to your industry?",
      footerTitle: "See how Omniweb fits your team, funnel, and revenue goals.",
      footerDescription: "These solution pages connect the platform capabilities to real business models, so visitors can see themselves in the workflow.",
      seed,
      stats: [
        { value: "1", label: "System" },
        { value: "24/7", label: "Lead handling" },
        { value: "10+", label: "Use cases" },
        { value: "0", label: "Manual triage" },
      ],
    }),
  ])
) as Record<string, PageEntry>
