import { buildPageEntry, type PageEntry } from "@/lib/marketing-page-data"

const primary = { label: "Try Live Demo", href: "/demo" }
const secondary = { label: "Install AI Agent", href: "/dashboard/widget-install" }

const solutionSeeds = [
  {
    slug: "shopify-ai-assistant",
    title: "Shopify AI Assistant",
    summary: "Help shoppers find products, answer pre-purchase questions, and recover revenue before they abandon the cart.",
    overview: [
      "Shopify stores invest heavily in traffic — paid ads, SEO, influencer partnerships, email campaigns — and then watch a large portion of that traffic leave without buying. The most common reason is not price or product fit. It is unanswered questions. A shopper who cannot figure out whether a product ships to their country, whether a size runs small, or whether the return policy covers their situation will leave rather than take a risk.",
      "Omniweb's Shopify AI Assistant plugs into your store and becomes the knowledgeable salesperson your traffic deserves. It reads your product catalog, your policies, your shipping rules, and your FAQs, and then answers every shopper question in real time — accurately, conversationally, and without any human involvement.",
      "Beyond answering questions, the assistant actively recovers revenue. When a shopper adds items to the cart and hesitates, the AI can proactively address the most common objections, offer reassurance on your return policy, and gently move them toward checkout. When a shopper leaves, an automated follow-up sequence reaches out with a relevant reminder.",
      "The result is more revenue from the same traffic — higher conversion rates, fewer abandoned carts, and a shopping experience that feels premium without requiring a support team to staff it.",
    ],
    problem: "Shoppers leave without buying when their questions go unanswered. Generic chatbots that cannot discuss specific products, policies, or availability create more frustration than they resolve. Support teams cannot be available 24/7 at the scale e-commerce demands.",
    solution: "Omniweb builds a deep understanding of your Shopify store — products, policies, inventory context, and FAQs — and uses that knowledge to engage shoppers in real time, resolve objections, and guide them toward purchase at every stage of the buying journey.",
    valueToIndustry: "The e-commerce industry benefits from a higher conversion standard. When stores can handle every shopper question instantly and personally, the gap between traffic investment and revenue tightens — making every marketing dollar more effective.",
    valueToUser: "Your store converts more of the traffic you are already paying for. Your support team handles fewer repetitive questions. Your customers have a better buying experience. And your revenue per visitor improves without increasing your ad spend.",
    outcome: "Higher checkout conversion rates, lower cart abandonment, and more repeat purchases from customers who had a positive buying experience. The AI pays for itself from the first recovered cart.",
    features: [
      "Full Shopify catalog and policy knowledge ingestion",
      "Real-time product question answering with accurate details",
      "Cart abandonment detection and recovery conversations",
      "Upsell and cross-sell suggestions during the shopping session",
      "Order status and shipping question handling",
      "Return and exchange policy explanation",
      "Lead capture for high-intent visitors who are not ready to buy",
      "Post-purchase follow-up and review request automation",
    ],
    useCases: [
      "Direct-to-consumer brands with high SKU catalogs where shoppers have many product questions",
      "Stores with complex shipping rules or international fulfillment policies",
      "Subscription and replenishment products where returning customer questions drive support volume",
      "High-ticket products where buyers need reassurance before committing",
      "Fashion and apparel stores where sizing and fit questions drive abandonment",
    ],
    howItWorks: [
      "Omniweb connects to your Shopify store and ingests your product catalog, collection structure, policies, FAQs, and any custom knowledge you add. The AI is ready to discuss any product in your store accurately.",
      "When a shopper has a question — about a product, the shipping timeline, or your returns process — the AI responds immediately from your actual store data, giving the shopper the confidence they need to proceed.",
      "After the conversation, follow-up automations trigger based on outcome: a purchase confirmation with related product suggestions, a cart recovery message for shoppers who left, or a review request for completed orders.",
    ],
    faq: [
      { question: "Does the AI stay accurate when my inventory or pricing changes?", answer: "Yes. Omniweb re-syncs with your Shopify store on a regular schedule and whenever you trigger a manual update. Price changes, new products, and policy updates are reflected in the AI's responses promptly." },
      { question: "Can it help with post-purchase questions?", answer: "Yes. The AI handles order status, shipping timeline, return initiation, and exchange questions — reducing the volume of support tickets your team needs to handle." },
      { question: "Does it work with Shopify Plus?", answer: "Yes. Omniweb is compatible with all Shopify plan tiers including Plus. Enterprise customization and headless Shopify configurations are supported with a brief setup session." },
    ],
    related: ["/features/ai-chat-assistants", "/features/website-knowledge-base", "/pricing/shopify"],
  },
  {
    slug: "local-service-businesses",
    title: "Local Service Businesses",
    summary: "Turn local traffic and inbound calls into booked jobs, cleaner intake, and faster follow-up.",
    overview: [
      "Local service businesses — cleaning companies, landscapers, electricians, locksmiths, pest control, and dozens of other trades — share a common revenue problem: the phone rings at the wrong time. A busy technician cannot take a call in the middle of a job. The office is swamped on Monday morning when every weekend emergency reaches out at once. And after five o'clock, the calls go to voicemail and the leads go cold.",
      "Omniweb gives local service businesses a front-of-house AI that never misses a call, never puts a customer on hold, and never has a bad day. It answers with the professionalism of a full-time receptionist, qualifies the service need and urgency, checks service area, and routes the caller to the right next step — booking, quote request, or callback queue.",
      "The system is designed around the realities of local service work: customers who need things fast, businesses with tight margins and limited admin staff, and conversion windows that close quickly when leads are not handled immediately. Omniweb removes the friction at every point where a local service business normally loses a lead.",
    ],
    problem: "Local service leads move quickly and respond poorly to delay. A homeowner with a plumbing emergency who gets voicemail will call the next number on the list. A business that cannot answer its phones during peak hours loses exactly the customers it should be winning.",
    solution: "Omniweb answers every call and chat inquiry immediately, qualifies the service need, and routes the interaction to the right next step — whether that is a booked appointment, a dispatch notification, or a queued callback with full context.",
    valueToIndustry: "The local services sector gets a reliable intake layer that works at scale. Businesses that previously had to choose between responsiveness and operational capacity can now be responsive without adding staff.",
    valueToUser: "You stop losing jobs to competitors who simply answered faster. Your dispatch and office team gets better-qualified job requests. Customers get an immediate, professional experience that makes your business look like a larger operation.",
    outcome: "More jobs booked, faster response times, and a reputation for reliability that generates repeat business and referrals. The AI handles the intake so your team can handle the work.",
    features: [
      "24/7 call and chat answering for all service inquiries",
      "Service area qualification to filter non-serviceable requests",
      "Urgency detection and priority routing for emergencies",
      "Quote request capture with job detail collection",
      "Appointment booking and dispatch queue management",
      "Automated follow-up for unanswered or incomplete requests",
      "Multi-channel coverage — phone, web chat, and text",
      "Seasonal volume handling without staffing spikes",
    ],
    useCases: [
      "HVAC and plumbing companies handling after-hours emergency calls",
      "Cleaning and maintenance services managing booking and scheduling",
      "Pest control and lawn care businesses qualifying seasonal demand",
      "Electrical and construction companies routing complex job inquiries",
      "Handyman services converting web and social traffic into bookings",
    ],
    howItWorks: [
      "When a customer calls or chats, the AI immediately identifies the service type, checks whether the location is within your service area, and assesses urgency. Emergency requests are flagged and escalated. Routine requests are processed and queued.",
      "The AI collects the specific job details the dispatcher or technician will need: location, access information, timing preference, and any relevant context about the problem. This reduces the back-and-forth that normally slows dispatch.",
      "The caller receives a confirmation of their request, a time expectation, and an automated follow-up if they have not been reached. Your team gets a clean, prioritized queue instead of a voicemail box.",
    ],
    faq: [
      { question: "What happens when a customer calls about an emergency?", answer: "The AI detects urgency signals in the conversation — language, context, and stated timeline — and escalates immediately. Emergency calls are flagged in the queue and can trigger a real-time notification to an on-call technician." },
      { question: "Can it handle multiple service types in one business?", answer: "Yes. You can configure separate qualification flows for different service categories, and the AI routes each inquiry to the appropriate queue based on what the customer describes." },
    ],
    related: ["/solutions/contractors", "/features/appointment-scheduling", "/pricing/combo"],
  },
  {
    slug: "contractors",
    title: "Contractors",
    summary: "Help contractors answer after-hours leads, qualify the job, and book more work without more office staff.",
    overview: [
      "Contracting is a relationship business that runs on responsiveness. The homeowner who just noticed a roof leak after a storm, the property manager who needs an electrician by end of week, the business owner whose HVAC failed in midsummer — all of them are making their decision about who to call based on who responds first and who sounds most competent when they do.",
      "Most contractor businesses lose leads not because they lack the skill or availability, but because their intake process does not scale. One office manager handles forty calls. The phone rings while the crew is in the truck. The website contact form sits unanswered until Monday. By the time a callback is made, the job has been awarded to whoever was reachable.",
      "Omniweb gives contractors a professional, always-on intake system that answers calls and web inquiries immediately, qualifies the job type, location, and urgency, and delivers clean job requests to the right person without any admin overhead. It handles the volume that manual intake cannot, and it does it with the professionalism that builds trust with property owners and property managers.",
    ],
    problem: "Contractors miss revenue not because they lack capacity, but because their intake cannot keep up with demand. Every unanswered call after hours, every web form that sits unread over the weekend, and every delayed callback is a job that went to a competitor who simply picked up the phone.",
    solution: "Omniweb provides contractors with an always-on intake system that handles calls, chat, and form submissions — qualifying the job type, collecting the relevant details, and routing the request into the right workflow so the team can respond to real opportunities without sorting through noise.",
    valueToIndustry: "The contracting industry gets a more professional and scalable intake model. Smaller shops can compete with larger companies on responsiveness, and larger operations can maintain quality intake even during peak demand.",
    valueToUser: "You win more jobs from the leads you were already generating — because you respond faster, qualify better, and show up to the right jobs. Your admin load decreases while your booked work increases.",
    outcome: "More booked jobs per lead generated. Faster response times that build your reputation for reliability. Cleaner job intake that saves your dispatcher hours of triage every week.",
    features: [
      "After-hours and weekend call answering",
      "Job type qualification — roofing, HVAC, plumbing, electrical, and more",
      "Location and service area validation",
      "Urgency detection and priority flagging",
      "Estimate request capture with detailed job information",
      "Booking and callback scheduling",
      "Automated follow-up for warm leads that did not close immediately",
      "Text and email job confirmation to the customer",
    ],
    useCases: [
      "Roofing contractors handling storm-damage inquiry surges after weather events",
      "HVAC companies managing high-volume seasonal demand for tune-ups and replacements",
      "Plumbing companies covering emergency calls outside normal business hours",
      "General contractors qualifying projects before committing to an on-site estimate",
      "Electrical and specialty trade contractors screening commercial and residential inquiries",
    ],
    howItWorks: [
      "The AI answers the call or chat, identifies itself as representing your business, and opens with the qualification questions that matter for your trade: what is the job, where is the property, how urgent is it, and what has already been tried.",
      "Based on the answers, the system classifies the request — emergency dispatch, scheduled estimate, or general inquiry — and routes it accordingly. High-urgency jobs trigger immediate notification. Scheduled jobs go into the calendar queue.",
      "The customer receives a confirmation of their request and a follow-up message at the scheduled time. Your team receives a complete job brief with all the details they need to prepare — without spending time on the intake call themselves.",
    ],
    faq: [
      { question: "Can it handle calls for multiple trade types within one business?", answer: "Yes. If your company offers multiple services — plumbing and HVAC, for example — the AI qualifies which service applies and routes each request to the appropriate team or queue." },
      { question: "How does it handle customers who want to negotiate or discuss scope in detail?", answer: "The AI handles initial qualification and basic scope collection. When a customer needs a detailed technical discussion, the AI flags the lead as high-intent and routes it to a senior estimator for a direct follow-up." },
    ],
    related: ["/features/ai-voice-agents", "/features/email-follow-up", "/pricing/ai-telephony"],
  },
  {
    slug: "real-estate",
    title: "Real Estate",
    summary: "Qualify buyers and renters, keep tours moving, and reduce the time between inquiry and showing.",
    overview: [
      "Real estate leads are time-sensitive in both directions. A buyer who inquires about a property and does not hear back within an hour will move on to the next listing. A renter who submits an application on a Friday afternoon will not wait until Monday for a response. The agent or property manager who responds first, asks the right questions, and schedules the showing immediately wins the client.",
      "Omniweb gives real estate professionals an AI that handles every inquiry the moment it arrives — whether it comes through the website, a listing platform, a phone call, or a text. The AI qualifies the buyer or renter (timeline, budget, requirements, financing status), answers questions about the property from the listing details, and schedules the showing directly on the agent's calendar.",
      "For property managers, the system handles the volume of rental inquiries that makes manual screening unsustainable. For individual agents, it provides the responsiveness of a full-time assistant without the cost of hiring one.",
    ],
    problem: "Real estate leads go cold faster than almost any other category. A buyer who does not hear back within 30 minutes of their inquiry is already looking at other properties. The agents and firms that win business are the ones who respond immediately, qualify intelligently, and schedule the next step before the lead cools.",
    solution: "Omniweb responds to every real estate inquiry the moment it arrives, qualifies the buyer or renter with the right questions, answers property questions from your listing knowledge, and schedules showings directly into the agent's calendar — all automatically.",
    valueToIndustry: "The real estate industry benefits from a higher standard of lead responsiveness. Properties get shown to better-qualified buyers. Agents spend their time with clients who are ready to act rather than sorting through cold inquiries.",
    valueToUser: "You never lose a lead because you were busy showing another property. Every inquiry gets an immediate, qualified response. Your showing calendar fills with high-intent prospects who already know the key details.",
    outcome: "More inquiries convert to showings. More showings convert to offers. Agents spend more time closing and less time chasing. Rental properties get filled faster with better-screened tenants.",
    features: [
      "Immediate response to property inquiries from all channels",
      "Buyer and renter qualification — timeline, budget, requirements",
      "Property detail Q&A from listing information",
      "Showing scheduling directly into agent calendars",
      "Pre-qualification status collection for buyer leads",
      "Automated follow-up for inquiries that did not book a showing",
      "Rental application pre-screening",
      "Multi-listing support for teams and brokerages",
    ],
    useCases: [
      "Real estate agents handling buyer inquiries for active listings",
      "Property management companies screening rental applicants at scale",
      "Real estate brokerages distributing leads to the right agents based on qualification",
      "New development sales teams managing pre-sale interest lists",
      "Commercial real estate professionals qualifying tenant and investor inquiries",
    ],
    howItWorks: [
      "The AI receives the inquiry and immediately identifies the property of interest. It asks the qualification questions that matter: how soon the buyer or renter is looking to move, what their budget is, whether they have been pre-approved, and what their specific requirements are.",
      "Using the property listing information, the AI answers specific questions about the property — features, pricing, availability, neighborhood details — so the prospect has the information they need to decide whether to schedule a showing.",
      "The showing is scheduled directly into the agent's calendar, a confirmation is sent to both parties, and the agent receives a lead brief with the full qualification context so they can prepare for the showing conversation.",
    ],
    faq: [
      { question: "Can it pull information from MLS listings automatically?", answer: "Omniweb can be configured to ingest listing data from your MLS, website, or manually uploaded property sheets. The AI uses this data to answer property-specific questions accurately." },
      { question: "How does it handle multiple agents in a brokerage?", answer: "Lead routing rules can distribute inquiries to agents based on geography, property type, specialization, or round-robin. Each agent has their own calendar and qualification queue." },
    ],
    related: ["/features/appointment-scheduling", "/features/website-knowledge-base", "/pricing/enterprise"],
  },
  {
    slug: "healthcare",
    title: "Healthcare",
    summary: "Support patient intake, scheduling, reminders, and common questions with a calm, responsive AI layer.",
    overview: [
      "Healthcare organizations face a communication paradox: the patients who need to reach them most urgently are often the ones most frustrated by hold times, unreturned calls, and confusing intake processes. Front-desk staff are stretched handling insurance verifications, appointment scheduling, prescription questions, and referral coordination simultaneously — and every task they cannot complete immediately is a patient experience that falls short.",
      "Omniweb provides healthcare organizations with an AI communication layer that handles the high-volume, lower-complexity interactions so clinical staff can focus on care. Appointment scheduling, common clinical questions, insurance and billing FAQs, and general navigation — all of these can be handled by an AI that is always available, never puts patients on hold, and communicates with calm, clear language.",
      "The system is designed with sensitivity to the healthcare context. Patients receive the same attentive, respectful communication whether they call at 9 AM or 2 AM. Responses are accurate and grounded in the organization's actual protocols. And anything that requires clinical judgment is escalated to the appropriate staff member with full context.",
    ],
    problem: "Healthcare front-desk teams are overwhelmed, and patients experience the consequences: long hold times, unreturned calls, scheduling delays, and repeated intake questions. These friction points directly affect patient satisfaction, appointment adherence, and trust in the organization.",
    solution: "Omniweb handles the high-volume communication layer — scheduling, reminders, FAQs, and general navigation — so clinical staff can focus on clinical work. Every patient interaction is handled immediately, professionally, and with accurate information drawn from the organization's own protocols.",
    valueToIndustry: "Healthcare organizations that invest in communication infrastructure see better patient retention, higher appointment adherence, and improved satisfaction scores. The industry benefits from a model that combines efficiency with genuine patient care.",
    valueToUser: "Administrative staff handle fewer repetitive inquiries and have more time for complex patient needs. Patients experience less frustration and more confidence in the organization's responsiveness.",
    outcome: "Lower no-show rates due to automated reminders. Shorter hold times because common questions are handled by AI. Higher patient satisfaction from consistent, immediate, professional communication.",
    features: [
      "Appointment scheduling and rescheduling via voice and chat",
      "Automated appointment reminders with response handling",
      "New patient intake question collection",
      "Insurance and billing FAQ handling",
      "Common clinical question answering from approved protocols",
      "Referral and escalation routing to clinical staff",
      "Multi-language patient communication",
      "After-hours response for urgent navigation questions",
    ],
    useCases: [
      "Primary care practices managing high appointment scheduling volume",
      "Specialty clinics handling referral and intake coordination",
      "Dental and optometry practices reducing no-shows with automated reminders",
      "Mental health providers managing new patient onboarding sensitively",
      "Multi-location health systems standardizing patient communication across sites",
    ],
    howItWorks: [
      "Patients interact with the AI through phone, the practice website, or a patient portal integration. The AI identifies the need — scheduling, billing question, clinical question, or referral — and routes accordingly.",
      "Scheduling requests are matched against provider availability in real time. Patients select from available slots, receive confirmation, and are added to the reminder sequence automatically.",
      "Clinical and complex questions are routed to the appropriate staff member with a summary of the patient's question and any relevant context collected during the conversation.",
    ],
    faq: [
      { question: "Is the AI HIPAA compliant?", answer: "Omniweb's healthcare configuration is built with HIPAA considerations in mind, including data handling, conversation logging permissions, and access controls. Contact us to review the compliance details for your specific use case." },
      { question: "Can it handle prescription refill requests?", answer: "The AI can collect the relevant information for a refill request — patient name, medication, prescriber — and route it to the appropriate clinical staff for review and processing. It does not make clinical decisions." },
    ],
    related: ["/features/multilingual-ai", "/features/appointment-scheduling", "/pricing/enterprise"],
  },
  {
    slug: "home-services",
    title: "Home Services",
    summary: "Turn home-service inquiries into booked visits with quick answers, routing, and automated follow-up.",
    overview: [
      "Home service customers have high urgency and low patience. When the water heater breaks, the pest problem flares up, or the gutters need cleaning before winter, the customer wants help today — and they will call or click through several providers until one responds quickly enough to earn the job.",
      "Omniweb gives home service businesses the intake speed that converts first-contact into booked visits. Every inquiry — phone, website chat, or text — is answered immediately. The AI asks the right questions to qualify the job and confirm the service area, and then books the visit or queues the callback automatically.",
      "For businesses that experience seasonal volume spikes, Omniweb handles the surge without requiring temporary staff. When spring cleaning, summer HVAC, and fall gutter seasons arrive, every inquiry gets the same fast, professional response regardless of how many come in simultaneously.",
    ],
    problem: "Home service customers contact multiple providers and book with whoever responds first. Businesses that take hours to respond or fail to follow up on web inquiries lose those jobs to faster competitors — even when their pricing and quality are better.",
    solution: "Omniweb answers every home service inquiry immediately, qualifies the job, and converts the first contact into a booked visit or a committed callback — before the customer has time to try the next provider on their list.",
    valueToIndustry: "Faster intake across the home services industry means fewer lost jobs, better customer experiences, and stronger businesses. The market benefits when responsiveness is the standard rather than the exception.",
    valueToUser: "You book more jobs from your current lead volume. Your team arrives at jobs that are already well-scoped and confirmed. Your customer reviews improve because the experience starts well from the first contact.",
    outcome: "More inquiries convert to booked visits. Fewer leads are lost to competitor response speed. Your team handles more jobs with the same admin capacity.",
    features: [
      "Instant multi-channel inquiry response — phone, chat, text",
      "Service area confirmation and routing",
      "Job type and scope collection before dispatch",
      "Real-time booking and calendar integration",
      "Automated follow-up for unbooked inquiries",
      "Seasonal volume handling without staffing increases",
      "Customer confirmation messages and reminders",
      "Post-service follow-up and review request sequences",
    ],
    useCases: [
      "Cleaning services booking recurring and one-time appointments",
      "Pest control companies handling seasonal inquiry surges",
      "Gutter and exterior cleaning services managing peak season volume",
      "Handyman and home repair services converting web leads to visits",
      "Pool and lawn maintenance companies managing service area inquiries",
    ],
    howItWorks: [
      "The customer calls or submits a chat inquiry. The AI greets them professionally, identifies the service need, and asks the qualification questions: what is the issue, where is the property, when do they need service.",
      "Once the job is qualified and the service area is confirmed, the AI presents available time slots or queues the lead for a callback at the customer's preferred time. The booking is confirmed and a reminder is scheduled.",
      "After the service visit, the AI sends a follow-up message — checking on satisfaction, requesting a review, and offering to schedule the next visit if applicable.",
    ],
    faq: [
      { question: "Can it handle multi-step jobs that need an on-site estimate before booking?", answer: "Yes. For jobs that require an estimate visit before the service is scheduled, the AI books the estimate appointment and collects the job details for the estimator to review before arrival." },
      { question: "Does it handle recurring service customers differently?", answer: "Yes. You can configure the AI to recognize returning customers and handle their inquiries with appropriate context — including their service history, preferences, and typical scheduling patterns." },
    ],
    related: ["/features/lead-automation", "/features/email-follow-up", "/solutions/local-service-businesses"],
  },
  {
    slug: "ecommerce",
    title: "Ecommerce",
    summary: "Support shopping journeys with instant answers, smart routing, and a conversion-first AI assistant.",
    overview: [
      "E-commerce stores operate in a competitive environment where the difference between a sale and a bounce is often measured in seconds. A shopper who cannot find the answer to their question will not wait — they will navigate to a competitor who makes the buying decision easier. Traffic is expensive. Converting the traffic you have is where the real leverage is.",
      "Omniweb's e-commerce AI sits on your store and provides the instant, knowledgeable response that turns browsers into buyers. It understands your product catalog, your shipping policies, your return guarantees, and your sizing or compatibility information — and it delivers that information in the moment a shopper needs it, in the conversation that is already happening on your page.",
      "Beyond answering questions, the AI actively moves shoppers through the funnel. It suggests complementary products when a shopper asks about one item. It reassures hesitant buyers about returns and warranties. It recovers abandoned carts with a timely, personalized follow-up. And it captures contact details from high-intent visitors who are not quite ready to purchase — creating a lead list that your email campaigns can convert over time.",
    ],
    problem: "E-commerce traffic is expensive and conversion rates are low. Most stores convert less than three percent of their visitors. The gap between traffic investment and revenue is largely explained by unanswered questions, unaddressed objections, and missed recovery opportunities.",
    solution: "Omniweb installs on your store and converts more of your existing traffic by answering every shopper question immediately, handling objections conversationally, recovering abandoned sessions, and capturing leads from high-intent visitors who are not yet ready to purchase.",
    valueToIndustry: "Higher e-commerce conversion rates mean better returns on marketing investment across the industry. When stores can reliably answer shopper questions and handle objections, the standard for online shopping experience improves.",
    valueToUser: "You get more revenue from your current traffic. Your customer support volume decreases because common questions are handled by the AI. Your email list grows from lead captures. Your cart recovery rate improves.",
    outcome: "Higher conversion rates, lower abandonment, more recovered carts, and a larger qualified email list — all from the traffic you are already generating.",
    features: [
      "Product catalog and policy knowledge ingestion",
      "Instant product question answering",
      "Cart abandonment detection and recovery conversations",
      "Upsell and cross-sell suggestions during sessions",
      "Return and shipping policy explanation",
      "Lead capture from high-intent visitors",
      "Post-purchase follow-up and review request automation",
      "Multi-language support for international stores",
    ],
    useCases: [
      "DTC brands with high-SKU catalogs where product questions drive abandonment",
      "Subscription product stores where recurring billing questions are common",
      "High-ticket items where buyers need confidence before purchasing",
      "Fashion and apparel stores where sizing is a major hesitation driver",
      "Specialty and niche stores where product knowledge creates a significant buyer advantage",
    ],
    howItWorks: [
      "Omniweb connects to your store platform, ingests your catalog and policies, and deploys the AI assistant on your site. The assistant is ready for visitors immediately and learns from your product updates on an ongoing basis.",
      "Shoppers interact with the AI naturally — asking questions, requesting comparisons, and raising objections. The AI responds with accurate, specific information drawn from your actual products and policies.",
      "When a shopper session ends without a purchase, the recovery sequence activates. A follow-up message reaches the shopper within the configured window with a relevant, personalized message tied to what they were looking at.",
    ],
    faq: [
      { question: "Which e-commerce platforms does Omniweb support?", answer: "Omniweb has native integration with Shopify and supports Shopify Plus. For other platforms including WooCommerce, BigCommerce, and custom storefronts, we support integration via embed script and API." },
      { question: "How does the AI handle out-of-stock products?", answer: "The AI checks product availability as part of its knowledge base sync. When a product is out of stock, the AI can inform the shopper, suggest alternatives, and offer to notify them when the item is restocked." },
    ],
    related: ["/solutions/shopify-ai-assistant", "/features/ai-chat-assistants", "/pricing/shopify"],
  },
  {
    slug: "professional-services",
    title: "Professional Services",
    summary: "Qualify consultations, capture context, and keep client intake organized from the first touch.",
    overview: [
      "Professional services firms — law firms, consulting practices, accounting offices, financial advisors — compete on trust and expertise. The initial contact from a prospective client is the first impression that sets the tone for everything that follows. A slow response, a generic intake form, or a confusing contact process signals that the firm is not organized, not attentive, or not interested in the client's business.",
      "Omniweb gives professional services firms an intake experience that is as polished as the services they deliver. When a prospective client reaches out — through the website, a referral link, or a phone call — the AI responds immediately, introduces the firm professionally, asks the right qualifying questions for the type of matter, and either schedules a consultation or routes the inquiry to the appropriate attorney, advisor, or consultant.",
      "The intake AI does more than filter leads. It captures the context that makes the first human conversation productive: the client's situation, their timeline, their primary concern, and what they have already tried. Partners and senior staff arrive at consultations prepared, which shortens the sales cycle and improves the client experience from the first call.",
    ],
    problem: "Professional services firms lose prospective clients because their intake process is slow, generic, or inconsistent. A prospect who reaches out on Tuesday and does not hear back until Thursday has already contacted two other firms. The intake experience is a sales asset that most firms underinvest in.",
    solution: "Omniweb provides professional services firms with an AI intake layer that responds to every inquiry immediately, collects the right context for the specific matter type, and routes qualified prospects to the appropriate advisor — with all the information needed for a productive first conversation already captured.",
    valueToIndustry: "Better intake processes improve conversion rates across professional services. When firms respond faster and arrive at consultations better prepared, both the firm's close rate and the client's experience improve.",
    valueToUser: "You convert more prospective clients from your current inquiry volume. Your attorneys, advisors, and consultants spend their consultation time on substance rather than basic intake questions. Your intake process reflects the quality of the work you do.",
    outcome: "Higher consultation conversion rates, shorter sales cycles, more productive first meetings, and a client intake experience that differentiates your firm from competitors still relying on contact forms and next-day callbacks.",
    features: [
      "Immediate response to website, phone, and referral inquiries",
      "Matter-type qualification for routing and preparation",
      "Consultation scheduling with intake context pre-captured",
      "Conflict check data collection",
      "FAQ handling for common service and pricing questions",
      "Automated follow-up for prospects who did not book",
      "Referral tracking and partner routing",
      "Multi-practice area support for full-service firms",
    ],
    useCases: [
      "Law firms qualifying new matter inquiries before first attorney contact",
      "Financial advisory practices screening prospective clients for AUM and service fit",
      "Consulting firms qualifying project scope before principal involvement",
      "Accounting firms managing seasonal inquiry volume during tax and compliance periods",
      "HR and executive search firms handling candidate and client intake",
    ],
    howItWorks: [
      "The AI receives the inquiry and identifies the type of matter or service being requested. It asks the qualification questions appropriate to that matter type — not a generic contact form, but a focused intake that mirrors what your intake team would ask.",
      "Once qualified, the AI either schedules a consultation directly into the relevant advisor's calendar or routes the inquiry with a complete intake brief for review and scheduling.",
      "Before the consultation, the AI sends the prospect a confirmation with any preparation materials, and the advisor receives a brief summarizing everything collected during intake — so the conversation can begin at substance rather than basics.",
    ],
    faq: [
      { question: "Can it handle different intake flows for different practice areas?", answer: "Yes. You can configure separate qualification flows for different service types — litigation vs. transactional matters, for example — and the AI routes each inquiry through the appropriate flow based on what the prospect describes." },
      { question: "How does it handle inquiries that are clearly not the right fit for the firm?", answer: "You can configure the AI to recognize out-of-scope inquiries and handle them respectfully — either declining politely and providing a referral resource, or collecting contact details for a brief callback to confirm the situation." },
    ],
    related: ["/features/lead-automation", "/features/appointment-scheduling", "/pricing/agency"],
  },
  {
    slug: "roadside-assistance",
    title: "Roadside Assistance",
    summary: "Capture urgent dispatch details quickly so help can be routed with less confusion and delay.",
    overview: [
      "Roadside assistance is the highest-stakes intake scenario in service businesses. The customer is stranded, stressed, and needs a clear response and a realistic ETA — not a hold queue, not a callback, not an email form. Every second of delay in the intake process is a second the customer's frustration is building and their trust in your service is declining.",
      "Omniweb's roadside configuration is designed for speed and precision. The AI picks up immediately, identifies the type of incident, captures the exact location, assesses the urgency, and routes the dispatch request with all the information the technician needs to respond effectively.",
      "The system handles the communication layer so your dispatch team can focus on routing, not intake. When volume spikes — during severe weather, major accidents, or seasonal demand peaks — Omniweb handles every call simultaneously, so no customer waits on hold while a single dispatcher takes the call ahead of them.",
    ],
    problem: "Roadside customers who are put on hold, sent to voicemail, or subjected to a long intake process will call a competitor immediately. In this category, speed is the service. Every minute the customer waits for a clear response is a minute they are more likely to escalate, complain, or cancel.",
    solution: "Omniweb provides immediate call pickup, fast and precise incident capture, and automatic dispatch routing — handling the intake layer so your team can focus on getting the technician to the right place at the right time.",
    valueToIndustry: "Faster intake reduces the time between incident and dispatch, which improves both customer satisfaction and technician utilization. The industry benefits from a more efficient connection between customer need and service response.",
    valueToUser: "You handle more incidents simultaneously without additional dispatcher headcount. Customer satisfaction improves because every caller gets an immediate response. Technicians arrive with better information because the intake was thorough and structured.",
    outcome: "Faster dispatch, higher customer satisfaction, and more incidents handled per hour with the same team. The reputation benefits of being reliably fast and professional compound into more service contracts and renewals.",
    features: [
      "Immediate call pickup — zero hold time",
      "Incident type classification — tow, battery, flat, fuel, lockout",
      "Precise location capture and confirmation",
      "ETA communication to the customer",
      "Dispatch routing with complete incident brief",
      "Customer SMS updates during response",
      "Multi-incident simultaneous handling",
      "Priority escalation for safety-critical situations",
    ],
    useCases: [
      "Towing and recovery companies handling inbound dispatch calls",
      "Roadside assistance membership programs managing member incidents",
      "Fleet management companies handling driver emergency calls",
      "Insurance-provided roadside programs routing customer calls",
      "Auto clubs and membership organizations managing high call volume",
    ],
    howItWorks: [
      "The AI answers the call immediately and identifies the incident type from the first few words. It asks for the exact location using landmark and street address confirmation to ensure precision.",
      "The incident is classified by urgency — safety-critical incidents are flagged for immediate dispatch. Standard incidents enter the queue with the full incident brief attached.",
      "The customer receives an SMS confirmation with the expected arrival time. Dispatch receives the complete incident record with location, incident type, and any relevant context the customer provided.",
    ],
    faq: [
      { question: "What if the customer is in a location with poor cellular signal?", answer: "The AI is designed to gather critical information quickly in the early part of the call in case the connection degrades. Location and incident type are captured first, before additional qualification questions." },
      { question: "Can it handle calls in multiple languages?", answer: "Yes. Omniweb's multilingual capability applies to roadside assistance as well. The AI detects the caller's language and responds accordingly, which is particularly important for roadside scenarios where stress may make communication in a second language harder." },
    ],
    related: ["/features/ai-voice-agents", "/features/lead-automation", "/pricing/ai-telephony"],
  },
  {
    slug: "ai-agency",
    title: "AI Agency",
    summary: "Package, deploy, and manage AI revenue systems for clients with a repeatable delivery model.",
    overview: [
      "AI agencies face a fundamental build vs. scale tension. Every client deployment built from scratch takes weeks of setup, custom configuration, and testing. As the client list grows, so does the operational complexity — managing multiple configurations, ensuring consistent quality across accounts, and delivering the AI promise without a proportionally growing team.",
      "Omniweb gives AI agencies a platform built for multi-tenant deployment. Instead of building each client's AI system from a blank canvas, agencies configure from a proven set of templates and workflows, adapt them to the client's specific business context, and deploy with significantly less time investment per account. The client gets a fully customized AI system. The agency gets a delivery model that scales.",
      "Beyond deployment, Omniweb supports the ongoing managed service that makes agency relationships sticky. Client reporting, performance monitoring, conversation analytics, and workflow optimization — all of these are built into the platform so agencies can demonstrate value continuously rather than just at launch.",
    ],
    problem: "Most AI agencies struggle to deliver AI value efficiently because every client build is a custom project. Without a platform built for agency delivery, the cost of setup, management, and reporting scales linearly with client count — which caps revenue without improving margin.",
    solution: "Omniweb provides agencies with a multi-tenant platform designed for repeatable client deployment. Template-based configuration, centralized management, client-specific reporting, and white-label options let agencies deliver more with less operational overhead.",
    valueToIndustry: "The agency market benefits from a platform that makes AI deployment commercially viable for mid-market clients — not just enterprise. When delivery costs come down, more businesses can access professionally deployed AI revenue systems.",
    valueToUser: "Your agency can take on more clients, deliver faster, and maintain higher quality across accounts. Your margin improves because you are not rebuilding from scratch on every engagement. Your clients get better outcomes because you are working from proven deployment patterns.",
    outcome: "More client deployments per quarter. Faster time-to-live per client. Higher client retention because managed service reporting demonstrates clear, ongoing value. Better margins because the delivery model is repeatable.",
    features: [
      "Multi-tenant account management from a single dashboard",
      "White-label branding for client-facing interfaces",
      "Template-based deployment configuration",
      "Client-specific reporting and performance dashboards",
      "Cross-account analytics for benchmarking and optimization",
      "Role-based access control for team and client access",
      "Workflow template library for common vertical deployments",
      "Scalable infrastructure that grows with your client base",
    ],
    useCases: [
      "AI agencies managing AI voice and chat deployments for SMB clients",
      "Digital marketing agencies adding AI lead generation as a managed service",
      "Business process consultants delivering AI-powered intake and qualification systems",
      "Franchise system operators standardizing AI communication across locations",
      "SaaS resellers offering Omniweb under their own brand to their customer base",
    ],
    howItWorks: [
      "Agencies configure the Omniweb platform under their own branding. Client accounts are created within the agency's multi-tenant environment, each with its own knowledge base, qualification flows, and reporting configuration.",
      "For each new client, the agency selects the appropriate vertical template, adapts it to the client's specific business context, and deploys. The AI is configured with the client's knowledge base and tested before going live.",
      "After deployment, the client reporting dashboard shows conversation volume, lead quality, booking rates, and AI health metrics. The agency uses this data to demonstrate value, recommend optimizations, and retain the relationship over time.",
    ],
    faq: [
      { question: "Can we white-label the AI assistant with our agency's branding?", answer: "Yes. Omniweb supports full white-labeling of the client-facing AI assistant, including custom names, avatars, and brand styling. The agency brand is what the client's customers see." },
      { question: "How does pricing work for multi-client deployments?", answer: "Omniweb offers agency pricing tiers based on the number of active client accounts. Contact us to discuss the right tier for your current client base and growth projections." },
      { question: "Can we give clients their own login to view their reports?", answer: "Yes. You can create client-level access that gives the client visibility into their own reporting and conversation analytics without seeing other client accounts or agency-level settings." },
    ],
    related: ["/features/workflow-automation", "/resources/compare", "/pricing/agency"],
  },
]

export const solutionPages: Record<string, PageEntry> = Object.fromEntries(
  solutionSeeds.map((seed) => [
    seed.slug,
    buildPageEntry({
      sectionLabel: "SOLUTIONS",
      primaryAction: primary,
      secondaryAction: secondary,
      footerEyebrow: "Need a solution tailored to your industry?",
      footerTitle: "See how Omniweb fits your team, funnel, and revenue goals.",
      footerDescription: "Every solution is built on the same Omniweb platform — voice, chat, automation, and reporting — configured for the specific realities of your industry.",
      seed,
      stats: [
        { value: "1", label: "Unified system" },
        { value: "24/7", label: "Lead handling" },
        { value: "10+", label: "Industry solutions" },
        { value: "< 2s", label: "Response time" },
      ],
    }),
  ])
) as Record<string, PageEntry>
